/*
 * harness_flat.c - run one *lifted* function (tools/lift) on one test vector.
 *
 * The same line protocol as harness.c (see there), so run_vectors.py drives it unchanged:
 *     run_vectors.py --harness tools/difftest/build/harness-flat vector.json
 * The difference is the memory: lifted code reads and writes raw guest addresses, so the guest address space is one flat
 * array G, and there is no per-byte "was it defined" tracking to catch reads of memory the vector does not provide.
 * Instead every vector is run twice, with the undefined memory filled with two different bytes, and the runs must agree
 * on the return value, every written byte and every call made: if they do not, the function read something the vector
 * does not define.
 *
 * The low 16 MB of the guest (the program image) sit in G at their own addresses. The 1 MB blocks above that which a
 * vector touches (the heap, the stack of the thread the function was recorded on) are folded in behind them (lift_xl),
 * so a recorded stack pointer can be used as it is and pointers into the stack compare equal to the recording's. Writes
 * to the stack frame are not part of the compared output; every other byte the function stores to is, whatever value
 * it stores (the lifted code reports each store; a changed-bytes diff would miss a store of the value already there).
 * The function must be generated by tools/lift/gen_handlers.py (the LIFTED and LIFT_CALLEES tables).
 */
#include <setjmp.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "lift_rt.h"
#include "lift_tables.h"

#define LOW_SIZE 0x01000000u /* guest addresses below this are in G as they are */
#define HIGH_BLOCKS 16       /* 1 MB blocks above LOW_SIZE that can be folded in */
#define GSIZE (LOW_SIZE + HIGH_BLOCKS * 0x100000u)
#define STACK_LO 0x00f00000u /* with no recorded stack pointer, the stack is the top of the low memory */
#define STACK_TOP 0x00fff000u
#define FRAME_BELOW 0x200000u /* what the recorder counts as the stack frame: this far below ESP, up to the arguments */
#define MAX_ARGS 32
#define MAX_REGIONS 4096
#define MAX_CALLS 8192

uint8_t *G;

typedef struct {
    uint32_t addr;
    uint8_t *bytes;
    size_t len;
} Blob;

typedef struct {
    uint32_t addr, ret;
    int nargs;
    uint32_t args[MAX_ARGS];
    Blob *writes;
    int nwrites;
} Mock;

typedef struct {
    int made;
    uint32_t addr[MAX_CALLS];
    int nargs[MAX_CALLS];
    uint32_t args[MAX_CALLS][MAX_ARGS];
} CallLog;

static Blob *blobs;
static int nblobs;
static Mock *mocks;
static int nmocks;
static uint32_t read_addr[8192], read_len[8192];
static int nread_req;
static uint32_t high_block[HIGH_BLOCKS]; /* guest address >> 20 of each folded-in block */
static int nhigh;
static uint32_t stack_ptr;
static int have_stack_ptr;
static CallLog L;
static int next_mock;
static jmp_buf bail;
static char error_text[256];

static void die(const char *msg, const char *detail)
{
    printf("error %s%s%s\n", msg, detail ? ": " : "", detail ? detail : "");
    exit(3);
}

static uint32_t parse_u32(const char *s)
{
    char *end;
    unsigned long v;
    if (!s)
        die("missing number", NULL);
    v = strtoul(s, &end, 0);
    if (*end)
        die("bad number", s);
    return (uint32_t)v;
}

static int hexval(int c)
{
    return c >= '0' && c <= '9' ? c - '0' : c >= 'a' && c <= 'f' ? c - 'a' + 10 : c >= 'A' && c <= 'F' ? c - 'A' + 10 : -1;
}

static uint8_t *parse_hex(const char *s, size_t *len)
{
    size_t n = s ? strlen(s) : 0, i;
    uint8_t *out;
    if (n == 0 || n % 2)
        die("bad hex bytes", s);
    out = malloc(n / 2);
    for (i = 0; i < n / 2; i++) {
        int hi = hexval(s[2 * i]), lo = hexval(s[2 * i + 1]);
        if (hi < 0 || lo < 0)
            die("bad hex bytes", s);
        out[i] = (uint8_t)(hi << 4 | lo);
    }
    *len = n / 2;
    return out;
}

static void map_range(uint32_t addr, size_t len);

#ifdef LIFT_COVERAGE
/* The addresses of the instructions executed, appended to the file named by $FLAT_COV when the harness exits. */
static uint32_t *cov;
static size_t ncov, capcov;
void lift_cov(uint32_t a)
{
    size_t i;
    for (i = 0; i < ncov; i++)
        if (cov[i] == a)
            return;
    if (ncov == capcov)
        cov = realloc(cov, sizeof(uint32_t) * (capcov = capcov ? capcov * 2 : 1024));
    cov[ncov++] = a;
}
static void dump_cov(void)
{
    const char *path = getenv("FLAT_COV");
    FILE *f = path ? fopen(path, "a") : NULL;
    size_t i;
    if (!f)
        return;
    for (i = 0; i < ncov; i++)
        fprintf(f, "%x\n", cov[i]);
    fclose(f);
}
#endif

uint32_t lift_xl(uint32_t a)
{
    int i;
    if (a < LOW_SIZE)
        return a;
    for (i = 0; i < nhigh; i++)
        if (high_block[i] == a >> 20)
            return LOW_SIZE + (uint32_t)i * 0x100000u + (a & 0xfffffu);
    snprintf(error_text, sizeof(error_text), "access to 0x%08x, in memory the vector does not provide", a);
    longjmp(bail, 1);
}

/* Make sure every block of [addr, addr + len) can be addressed. */
static void map_range(uint32_t addr, size_t len)
{
    uint64_t end = (uint64_t)addr + (len ? len : 1), b;
    int i;
    if (end > 0x100000000ull)
        die("address range wraps around the 32-bit address space", NULL);
    for (b = addr >> 20; b <= (end - 1) >> 20; b++) {
        if (b < (LOW_SIZE >> 20))
            continue;
        for (i = 0; i < nhigh && high_block[i] != b; i++)
            ;
        if (i == nhigh) {
            if (nhigh >= HIGH_BLOCKS)
                die("the vector touches more distinct 1 MB blocks than the flat harness can fold in", NULL);
            high_block[nhigh++] = (uint32_t)b;
        }
    }
}

#ifdef LIFT_UNDEF_CHECK
static uint8_t *DEF;
static int undef_reports;
#endif
static uint8_t *WRT; /* bytes the lifted function stored to, whatever the value */
void lift_chk_write(uint32_t a, uint32_t n)
{
    uint32_t x = lift_xl(a);
    memset(WRT + x, 1, n);
#ifdef LIFT_UNDEF_CHECK
    memset(DEF + x, 1, n);
#endif
}
#ifdef LIFT_UNDEF_CHECK
void lift_chk_read(uint32_t a, uint32_t n)
{
    uint32_t i, x = lift_xl(a);
    for (i = 0; i < n; i++)
        if (!DEF[x + i] && undef_reports < 6) {
            fprintf(stderr, "undefined read of %u bytes at 0x%08x\n", n, a);
            undef_reports++;
            break;
        }
}
#endif

/* Store bytes into the guest, as setup or as a replayed callee's write (neither counts as the function's own stores). */
static void put(uint32_t addr, const uint8_t *b, size_t len)
{
    size_t i;
    map_range(addr, len);
    for (i = 0; i < len; i++) { /* a byte at a time: a block boundary may fall inside */
        uint32_t x = lift_xl(addr + (uint32_t)i);
        G[x] = b[i];
#ifdef LIFT_UNDEF_CHECK
        DEF[x] = 1;
#endif
    }
}

void lift_bad_jump(uint32_t from)
{
    snprintf(error_text, sizeof(error_text), "the jump at 0x%08x indexed past its table", from);
    longjmp(bail, 1);
}

LiftRegs lift_in, lift_out;   /* the flat harness has no registers to give: lifted code starts from zero */

uint32_t lift_call(uint32_t target, uint32_t argp, uint32_t *cleanup)
{
    const CalleeRow *row = NULL;
    CalleeRow dyn;
    Mock *m;
    int i;

    for (i = 0; i < LIFT_CALLEE_COUNT; i++)
        if (LIFT_CALLEES[i].addr == target)
            row = &LIFT_CALLEES[i];
    if (!row && next_mock < nmocks && mocks[next_mock].addr == target) {
        /* A target only known when it runs (a card's handler through the master table): the recorded call says how many
         * arguments it took, and handlers are cdecl. */
        dyn.addr = target;
        dyn.nargs = mocks[next_mock].nargs;
        dyn.cleanup = 0;
        row = &dyn;
    }
    if (!row) {
        snprintf(error_text, sizeof(error_text), "call to 0x%08x, which the generated table does not know", target);
        longjmp(bail, 1);
    }
    if (L.made >= MAX_CALLS) {
        snprintf(error_text, sizeof(error_text), "more than %d calls", MAX_CALLS);
        longjmp(bail, 1);
    }
    L.addr[L.made] = target;
    L.nargs[L.made] = row->nargs;
    for (i = 0; i < row->nargs && i < MAX_ARGS; i++)
        L.args[L.made][i] = RD32(argp + 4u * (uint32_t)i);
    L.made++;
    *cleanup = row->cleanup;

    if (next_mock >= nmocks) {
        snprintf(error_text, sizeof(error_text), "unexpected call to 0x%08x: the vector records no more calls", target);
        longjmp(bail, 1);
    }
    m = &mocks[next_mock++];
    if (m->addr != target) {
        snprintf(error_text, sizeof(error_text), "call %d went to 0x%08x but the vector expects 0x%08x", next_mock - 1, target,
                 m->addr);
        longjmp(bail, 1);
    }
    for (i = 0; i < m->nwrites; i++)
        put(m->writes[i].addr, m->writes[i].bytes, m->writes[i].len);
    return m->ret;
}

typedef struct {
    uint32_t ret;
    int bailed;
    int nregions;
    uint32_t raddr[MAX_REGIONS], rlen[MAX_REGIONS];
    uint8_t *rbytes[MAX_REGIONS];
    CallLog calls;
    uint8_t *reads[8192];
} Result;

static uint32_t orig_addr(uint32_t x)
{
    return x < LOW_SIZE ? x : (high_block[(x - LOW_SIZE) >> 20] << 20) | (x & 0xfffffu);
}

static void run_once(const LiftedFn *fn, const uint32_t *args, int nargs, uint8_t fill, Result *R)
{
    uint32_t esp, x, win_lo, win_hi;
    int i;

    memset(G, fill, GSIZE);
    memset(R, 0, sizeof(*R));
#ifdef LIFT_UNDEF_CHECK
    memset(DEF, 0, GSIZE);
    undef_reports = 0;
#endif
    for (i = 0; i < nblobs; i++)
        put(blobs[i].addr, blobs[i].bytes, blobs[i].len);
    L.made = 0;
    next_mock = 0;
    memset(WRT, 0, GSIZE);

    esp = have_stack_ptr ? stack_ptr : STACK_TOP - 4u * (uint32_t)(nargs + 1);
    win_lo = have_stack_ptr ? esp - FRAME_BELOW : STACK_LO; /* the stack frame: not part of the output */
    win_hi = have_stack_ptr ? esp + 4u + 4u * (uint32_t)nargs : LOW_SIZE;
    WR32(esp, 0xfeedfac0u); /* the return address */
    for (i = 0; i < nargs; i++)
        WR32(esp + 4u + 4u * (uint32_t)i, args[i]);

    if (setjmp(bail)) {
        R->bailed = 1;
    } else {
        R->ret = fn->fn(esp);
    }
    R->calls = L;

    /* The function's writes: every byte it stored to outside the stack frame, grouped into runs. */
    for (x = 0; x < GSIZE; x++) {
        uint32_t start = x, oa = orig_addr(x);
        if (!WRT[x] || (oa >= win_lo && oa < win_hi))
            continue;
        while (x + 1 < GSIZE && WRT[x + 1] && (x + 1 < LOW_SIZE || ((x + 1) & 0xfffffu)) &&
               !(orig_addr(x + 1) >= win_lo && orig_addr(x + 1) < win_hi))
            x++;
        if (R->nregions < MAX_REGIONS) {
            R->raddr[R->nregions] = oa;
            R->rlen[R->nregions] = x + 1 - start;
            R->rbytes[R->nregions] = malloc(x + 1 - start);
            memcpy(R->rbytes[R->nregions], G + start, x + 1 - start);
            R->nregions++;
        }
    }
    for (i = 0; i < nread_req; i++) {
        uint32_t k;
        R->reads[i] = malloc(read_len[i]);
        for (k = 0; k < read_len[i]; k++)
            R->reads[i][k] = G[lift_xl(read_addr[i] + k)];
    }
}

static int same(const Result *a, const Result *b)
{
    int i;
    if (a->ret != b->ret || a->bailed != b->bailed || a->nregions != b->nregions || a->calls.made != b->calls.made)
        return 0;
    for (i = 0; i < a->nregions; i++)
        if (a->raddr[i] != b->raddr[i] || a->rlen[i] != b->rlen[i] || memcmp(a->rbytes[i], b->rbytes[i], a->rlen[i]))
            return 0;
    for (i = 0; i < a->calls.made; i++) {
        if (a->calls.addr[i] != b->calls.addr[i] || memcmp(a->calls.args[i], b->calls.args[i], sizeof(a->calls.args[i])))
            return 0;
    }
    for (i = 0; i < nread_req; i++)
        if (memcmp(a->reads[i], b->reads[i], read_len[i]))
            return 0;
    return 1;
}

int main(void)
{
    static char line[1 << 23];
    const LiftedFn *fn = NULL;
    uint32_t args[MAX_ARGS], entry = 0;
    int nargs = 0, have_entry = 0, ran = 0, i, k;
    static Result r0, r1, r2, r3;
    Result *o;

#ifdef LIFT_COVERAGE
    atexit(dump_cov);
#endif
    G = calloc(1, GSIZE);
#ifdef LIFT_UNDEF_CHECK
    DEF = calloc(1, GSIZE);
#endif
    WRT = calloc(1, GSIZE);
    if (!G)
        die("out of memory", NULL);
    while (fgets(line, sizeof(line), stdin)) {
        char *cmd = strtok(line, " \t\r\n");
        if (!cmd || cmd[0] == '#')
            continue;
        if (strcmp(cmd, "program") == 0) {
            (void)strtok(NULL, " \t\r\n");
        } else if (strcmp(cmd, "function") == 0) {
            const char *name = strtok(NULL, " \t\r\n");
            for (i = 0; name && i < LIFTED_COUNT; i++)
                if (strcmp(LIFTED[i].name, name) == 0)
                    fn = &LIFTED[i];
            if (!fn)
                die("no lifted implementation of", name);
        } else if (strcmp(cmd, "entry") == 0) {
            entry = parse_u32(strtok(NULL, " \t\r\n"));
            have_entry = 1;
        } else if (strcmp(cmd, "esp") == 0) {
            stack_ptr = parse_u32(strtok(NULL, " \t\r\n"));
            have_stack_ptr = 1;
        } else if (strcmp(cmd, "arg") == 0) {
            if (nargs >= MAX_ARGS)
                die("too many arguments", NULL);
            args[nargs++] = parse_u32(strtok(NULL, " \t\r\n"));
        } else if (strcmp(cmd, "mem") == 0) {
            uint32_t addr = parse_u32(strtok(NULL, " \t\r\n"));
            size_t len;
            uint8_t *bytes = parse_hex(strtok(NULL, " \t\r\n"), &len);
            map_range(addr, len);
            blobs = realloc(blobs, sizeof(Blob) * (size_t)(nblobs + 1));
            blobs[nblobs].addr = addr;
            blobs[nblobs].bytes = bytes;
            blobs[nblobs].len = len;
            nblobs++;
        } else if (strcmp(cmd, "call") == 0) {
            Mock *m;
            mocks = realloc(mocks, sizeof(Mock) * (size_t)(nmocks + 1));
            m = &mocks[nmocks++];
            memset(m, 0, sizeof(*m));
            m->addr = parse_u32(strtok(NULL, " \t\r\n"));
            m->ret = parse_u32(strtok(NULL, " \t\r\n"));
            m->nargs = (int)parse_u32(strtok(NULL, " \t\r\n"));
            for (i = 0; i < m->nargs && i < MAX_ARGS; i++)
                m->args[i] = parse_u32(strtok(NULL, " \t\r\n"));
        } else if (strcmp(cmd, "callmem") == 0) {
            Mock *m;
            Blob *b;
            if (nmocks == 0)
                die("callmem before any call", NULL);
            m = &mocks[nmocks - 1];
            m->writes = realloc(m->writes, sizeof(Blob) * (size_t)(m->nwrites + 1));
            b = &m->writes[m->nwrites++];
            b->addr = parse_u32(strtok(NULL, " \t\r\n"));
            b->bytes = parse_hex(strtok(NULL, " \t\r\n"), &b->len);
            map_range(b->addr, b->len);
        } else if (strcmp(cmd, "read") == 0) {
            if (nread_req >= 8192)
                die("too many reads", NULL);
            read_addr[nread_req] = parse_u32(strtok(NULL, " \t\r\n"));
            read_len[nread_req] = parse_u32(strtok(NULL, " \t\r\n"));
            map_range(read_addr[nread_req], read_len[nread_req]);
            nread_req++;
        } else if (strcmp(cmd, "run") == 0) {
            ran = 1;
            break;
        } else {
            die("unknown command", cmd);
        }
    }
    if (!ran || !fn)
        die("a function and a run command are required", NULL);
    if (have_entry && entry != fn->entry) {
        char d[96];
        snprintf(d, sizeof(d), "%s is at 0x%08x, the vector says 0x%08x", fn->name, fn->entry, entry);
        die("entry address mismatch", d);
    }

    if (have_stack_ptr)
        map_range(stack_ptr - 0x10000u, 0x12000u); /* room for the function's frame below the stack pointer */
    /* Four fills: a comparison with a small constant gives the same answer under 0x00 and 0xff (both below it) and a
     * different one under 0x7f, so two fills can agree by luck. */
    run_once(fn, args, nargs, 0x00, &r0);
    run_once(fn, args, nargs, 0xa5, &r1);
    run_once(fn, args, nargs, 0xff, &r2);
    run_once(fn, args, nargs, 0x7f, &r3);
    o = !same(&r0, &r1) ? &r1 : !same(&r0, &r2) ? &r2 : &r3;
    if (getenv("FLAT_FILL")) { /* debugging: judge the vector on one fill only, whether or not they agree */
        o = &r0;
    }

    printf("retbits 32\n");
    if (r0.bailed) {
        printf("error %s\n", error_text);
    }
    if (!same(&r0, o)) {
        printf("error the result depends on memory the vector does not define (the fills gave different outputs)\n");
        if (r0.nregions != o->nregions)
            printf("error   %d written regions with one fill, %d with the other\n", r0.nregions, o->nregions);
        for (i = 0; i < r0.nregions && i < o->nregions; i++)
            if (r0.raddr[i] != o->raddr[i] || r0.rlen[i] != o->rlen[i] || memcmp(r0.rbytes[i], o->rbytes[i], r0.rlen[i]))
                printf("error   written region at 0x%08x (%u bytes) differs\n", r0.raddr[i], (unsigned)r0.rlen[i]);
        for (i = 0; i < r0.calls.made && i < o->calls.made; i++)
            if (r0.calls.addr[i] != o->calls.addr[i] || memcmp(r0.calls.args[i], o->calls.args[i], sizeof(r0.calls.args[i])))
                printf("error   call %d (0x%08x) is made with different arguments\n", i, r0.calls.addr[i]);
        if (r0.bailed != o->bailed)
            printf("error   one fill bails out (%s)\n", error_text);
        if (r0.ret != o->ret)
            printf("error   return value 0x%08x with one fill, 0x%08x with the other\n", r0.ret, o->ret);
        if (r0.calls.made != o->calls.made)
            printf("error   %d calls with one fill, %d with the other\n", r0.calls.made, o->calls.made);
        return 3;
    }
    if (!r0.bailed)
        printf("ret 0x%08x\n", r0.ret);
    for (i = 0; i < r0.calls.made; i++) {
        printf("call %d 0x%08x %d", i, r0.calls.addr[i], r0.calls.nargs[i]);
        for (k = 0; k < r0.calls.nargs[i] && k < MAX_ARGS; k++)
            printf(" 0x%08x", r0.calls.args[i][k]);
        printf("\n");
    }
    for (i = 0; i < r0.nregions; i++) {
        uint32_t j;
        printf("written 0x%08x ", r0.raddr[i]);
        for (j = 0; j < r0.rlen[i]; j++)
            printf("%02x", r0.rbytes[i][j]);
        printf("\n");
    }
    printf("faults 0\n");
    for (i = 0; i < nread_req; i++) {
        uint32_t j;
        printf("read 0x%08x ", read_addr[i]);
        for (j = 0; j < read_len[i]; j++)
            printf("%02x", r0.reads[i][j]);
        printf("\n");
    }
    return r0.bailed ? 3 : 0;
}
