#!/usr/bin/env python3
"""Audit reports around the verified-name registry. Writes two Markdown files:

- tools/registry/duplicates.md: every function name that more than one address carries in the same
  program's function_index.csv. A rename by name hits all of them (this happened with
  Glue_Subsystem_004cdb4f in DUEL.EXE). Groups that involve a registry-verified name or address are marked.
- tools/registry/generator_hits.md: lines in scripts/*.py and scripts/*.java, and in the root symbol-map
  CSVs those scripts read, that tie a registry address to a name other than the verified one, so that
  re-running them could bring an old name back. Nothing is edited.

    python3 tools/registry/audit_names.py
"""

import csv
import glob
import os
import re
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import registry as reg  # noqa: E402

DUPLICATES_MD = os.path.join(reg.HERE, "duplicates.md")
GENERATORS_MD = os.path.join(reg.HERE, "generator_hits.md")
QUOTED_RE = re.compile(r"\"([^\"\n]*)\"|'([^'\n]*)'")
IDENT_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
DEFAULT_PREFIXES = ("FUN_", "thunk_FUN_", "DAT_", "LAB_", "PTR_", "SUB_", "UNK_")


# --------------------------------------------------------------------------------------------------
# Duplicate names


def read_index_rows(program):
    path = os.path.join(reg.REPO, program.lower(), "function_index.csv")
    with open(path, newline="", encoding="utf-8", errors="replace") as f:
        return [(int(r["Address"], 16), r["FunctionName"], r["Filename"], int(r["BodySize"] or 0))
                for r in csv.DictReader(f)]


def filename_name(filename, addr):
    """The name a function had when it was exported: '<name>_<address>.c'."""
    suffix = f"_{addr:08x}.c"
    return filename[:-len(suffix)] if filename.lower().endswith(suffix) else None


def duplicate_groups(program, column="name"):
    groups = defaultdict(list)
    for addr, name, filename, size in read_index_rows(program):
        key = name if column == "name" else filename_name(filename, addr)
        if key:
            groups[key].append((addr, name, size))
    return {k: v for k, v in groups.items() if len({a for a, _, _ in v}) > 1}


def doc_mentions():
    """{address: [doc line numbers]} for every hex address written in SYMBOL_VERIFICATION.md."""
    out = defaultdict(list)
    with open(reg.DOC, encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            for m in re.finditer(r"(?<![0-9A-Za-z_])0x([0-9a-fA-F]{5,8})(?![0-9a-fA-F])", line):
                out[int(m.group(1), 16)].append(n)
    return out


def render_duplicates(rows):
    mentioned = doc_mentions()
    by_name = defaultdict(list)
    by_addr = {}
    for r in rows:
        by_name[r["name"]].append(r)
        by_addr[(r["program"], r["address"])] = r
    out = ["# Duplicate function names", "",
           "Generated by `audit_names.py`; do not edit by hand.", "",
           "A function name carried by more than one address in the same program's `function_index.csv`. "
           "Renaming by name (sed, a rename map keyed by the old name, a Ghidra script looking the name up) "
           "hits every address in the group, which is how the `Glue_Subsystem_004cdb4f` rename landed on two "
           "different `DUEL.EXE` functions. Rename these by address.", "",
           "**Registry** marks a group that involves a verified name (`name`: the shared name is a registry "
           "name, in either program) or a verified address (`address`: one of the addresses has a registry "
           "row in this program). `in the doc, not registered` flags an address `SYMBOL_VERIFICATION.md` "
           "writes down without a registry row (the doc does not say which program each prose address is in, "
           "so check the line).", ""]
    total = 0
    for program in reg.PROGRAMS:
        groups = duplicate_groups(program)
        total += len(groups)
        out += [f"## {program}.EXE: {len(groups)} shared names", ""]
        if not groups:
            out += ["None.", ""]
            continue
        out += ["| Name | Addresses (body size) | Registry |", "|---|---|---|"]
        for name in sorted(groups, key=lambda n: (-len(groups[n]), n)):
            members = sorted(groups[name])
            marks = []
            if name in by_name:
                progs = sorted({r["program"] for r in by_name[name]})
                marks.append(f"name ({', '.join(progs)})")
            verified = [a for a, _, _ in members if (program, a) in by_addr]
            if verified:
                marks.append("address " + ", ".join(f"`{reg.fmt_addr(a)}`" for a in verified))
            in_doc = [a for a, _, _ in members if a in mentioned and a not in verified]
            if in_doc:
                marks.append("in the doc, not registered: " + ", ".join(
                    f"`{reg.fmt_addr(a)}` (line {', '.join(map(str, sorted(set(mentioned[a]))))})" for a in in_doc))
            addrs = ", ".join(f"`{reg.fmt_addr(a)}` ({s})" for a, _, s in members)
            out.append(f"| `{name}` | {addrs} | {'; '.join(marks) or ''} |")
        out.append("")
    # Names that were shared when the functions were exported (the Filename column), now split.
    out += ["## Shared at export time, since split", "",
            "The `Filename` column of `function_index.csv` keeps the name a function had when the C files were "
            "exported. These names were carried by several addresses then and are no longer; a script or map "
            "that still uses the old name would hit all of them.", ""]
    any_hist = False
    for program in reg.PROGRAMS:
        current = duplicate_groups(program)
        current_sets = {frozenset(a for a, _, _ in v) for v in current.values()}
        hist = {k: v for k, v in duplicate_groups(program, "filename").items()
                if frozenset(a for a, _, _ in v) not in current_sets}
        if not hist:
            continue
        any_hist = True
        out += [f"### {program}.EXE", "", "| Name at export | Addresses and current names | Registry |",
                "|---|---|---|"]
        for name in sorted(hist):
            members = sorted(hist[name])
            verified = [a for a, _, _ in members if (program, a) in by_addr]
            marks = []
            if name in by_name:
                marks.append(f"name ({', '.join(sorted({r['program'] for r in by_name[name]}))})")
            if verified:
                marks.append("address " + ", ".join(f"`{reg.fmt_addr(a)}`" for a in verified))
            in_doc = [a for a, _, _ in members if a in mentioned and a not in verified]
            if in_doc:
                marks.append("in the doc, not registered: " + ", ".join(
                    f"`{reg.fmt_addr(a)}` (line {', '.join(map(str, sorted(set(mentioned[a]))))})" for a in in_doc))
            mark = "; ".join(marks)
            addrs = ", ".join(f"`{reg.fmt_addr(a)}` `{n}`" for a, n, _ in members)
            out.append(f"| `{name}` | {addrs} | {mark} |")
        out.append("")
    if not any_hist:
        out += ["None.", ""]
    return "\n".join(out), total


# --------------------------------------------------------------------------------------------------
# Generator scripts


def addr_pattern(addr):
    h = f"{addr:x}"
    return re.compile(rf"(?i)(?<![0-9a-f])(?:0x0{{0,{8 - len(h)}}}|0{{{8 - len(h)}}}){h}(?![0-9a-f])")


def is_default_name(s, addr):
    return s.startswith(DEFAULT_PREFIXES) and s.lower().endswith(f"{addr:08x}")


OTHER_BINARIES = ("deck", "magsnd", "magvid", "statwin")


def program_of(path):
    """MAGIC or DUEL when the file name says so, OTHER for another binary's map, else None."""
    base = os.path.basename(path).lower()
    if base.startswith(OTHER_BINARIES):
        return "OTHER"
    progs = [p for p in reg.PROGRAMS if p.lower() in base]
    return progs[0] if len(progs) == 1 else None


def looks_like_symbol(s, addr):
    return (IDENT_RE.match(s) and not is_default_name(s, addr)
            and not re.fullmatch(r"(?i)(0x)?[0-9a-f]+", s)
            and (any(c.isupper() for c in s) or "_" in s))


def hit(path, n, r, stale, text, file_prog):
    return {"file": os.path.relpath(path, reg.REPO), "line": n, "row": r, "stale": stale,
            "old": [x for x in stale if x in r["old_names"]],
            "other_program": file_prog is not None and file_prog != r["program"], "text": text.strip()}


def scan_script(path, rows):
    """Lines of a generator script that pair a registry address with another quoted name."""
    file_prog = program_of(path)
    with open(path, encoding="utf-8", errors="replace") as f:
        lines = f.read().split("\n")
    hits = []
    for r in rows:
        pat = addr_pattern(r["address"])
        for n, line in enumerate(lines, 1):
            if not pat.search(line):
                continue
            names = [a or b for a, b in QUOTED_RE.findall(line)]
            stale = [x for x in names if looks_like_symbol(x, r["address"]) and x != r["name"]]
            if stale:
                hits.append(hit(path, n, r, stale, line, file_prog))
    return hits


def scan_map(path, rows):
    """Rows of an Address,[OldName,]NewName map whose NewName for a registry address is another name."""
    file_prog = program_of(path)
    by_addr = defaultdict(list)
    for r in rows:
        by_addr[r["address"]].append(r)
    hits = []
    with open(path, newline="", encoding="utf-8", errors="replace") as f:
        reader = csv.DictReader(f)
        if not reader.fieldnames or "Address" not in reader.fieldnames or "NewName" not in reader.fieldnames:
            return hits
        for n, row in enumerate(reader, 2):
            try:
                a = int(row["Address"], 16)
            except (TypeError, ValueError):
                continue
            new = (row["NewName"] or "").strip()
            for r in by_addr.get(a, []):
                if new and new != r["name"] and not is_default_name(new, a):
                    hits.append(hit(path, n, r, [new], ",".join(row[k] or "" for k in reader.fieldnames),
                                    file_prog))
    return hits


def old_name_mentions(paths, rows):
    """Old names (not Ghidra defaults) that appear in a file with no registry address on the line."""
    out = []
    olds = {}
    for r in rows:
        for o in r["old_names"]:
            if not o.startswith(DEFAULT_PREFIXES) and not o.endswith("*"):
                olds.setdefault(o, []).append(r)
    if not olds:
        return out
    pat = re.compile(r"(?<![A-Za-z0-9_])(" + "|".join(map(re.escape, sorted(olds, key=len, reverse=True)))
                     + r")(?![A-Za-z0-9_])")
    for path in paths:
        with open(path, encoding="utf-8", errors="replace") as f:
            for n, line in enumerate(f, 1):
                for m in pat.finditer(line):
                    rs = olds[m.group(1)]
                    if any(addr_pattern(r["address"]).search(line) for r in rs):
                        continue
                    out.append((os.path.relpath(path, reg.REPO), n, m.group(1), rs, line.strip()))
    return out


def attach_old_names(rows):
    """Registry rows with the old names from the doc (the CSV keeps them only in the notes)."""
    parsed, _, _ = reg.parse_doc()
    olds = {(r["program"], r["address"]): r["old_names"] for r in parsed}
    for r in rows:
        r["old_names"] = olds.get((r["program"], r["address"]), [])
    return rows


def render_generators(rows):
    scripts = sorted(glob.glob(os.path.join(reg.REPO, "scripts", "*.py"))
                     + glob.glob(os.path.join(reg.REPO, "scripts", "*.java")))
    maps = [p for p in sorted(glob.glob(os.path.join(reg.REPO, "*.csv"))) if program_of(p) != "OTHER"]
    script_hits = [h for p in scripts for h in scan_script(p, rows)]
    map_hits = [h for p in maps for h in scan_map(p, rows)]
    mentions = old_name_mentions(scripts, rows)

    def table(hits):
        lines = ["| File:line | Registry | Other name(s) on the line | Old name from the doc? | Line |",
                 "|---|---|---|---|---|"]
        for h in sorted(hits, key=lambda h: (h["file"], h["line"])):
            r = h["row"]
            reg_cell = f"{r['program']} `{reg.fmt_addr(r['address'])}` `{r['name']}`"
            if h["other_program"]:
                reg_cell += " (file looks like the other program)"
            text = h["text"].replace("|", "\\|")
            if len(text) > 140:
                text = text[:137] + "..."
            lines.append(f"| `{h['file']}:{h['line']}` | {reg_cell} | "
                         f"{', '.join(f'`{s}`' for s in h['stale'])} | "
                         f"{'yes: ' + ', '.join(h['old']) if h['old'] else 'no'} | `{text}` |")
        return lines

    out = ["# Generators that could bring an old name back", "",
           "Generated by `audit_names.py`; do not edit by hand. Nothing listed here has been changed.", "",
           "Each row is a line that mentions a registry address (as `0x0047496b`, `0047496b` or inside a name "
           "such as `FUN_0047496b`) together with a quoted name that is not the verified one. Ghidra default "
           "names for the same address (`FUN_`, `DAT_`, ...) are ignored: they are the lookup key of a rename, "
           "not its result, and so are bare lower-case words such as dictionary keys. A line can still be harmless (a comment, an address list, the old side of a "
           "rename pair); read it before acting. Every program loads at `0x00400000`, so a `DUEL.EXE` script "
           "can name a different function at a `MAGIC.EXE` registry address; such rows are marked.", "",
           f"## scripts/*.py and scripts/*.java: {len(script_hits)} lines", ""]
    out += table(script_hits) if script_hits else ["None."]
    out += ["", f"## Root symbol-map CSVs the scripts read: {len(map_hits)} lines", "",
            "Not scripts, but the generators read and rewrite them, so a stale row here comes back the same way. "
            "Only the `NewName` column counts (the name a rename would write); maps of other binaries "
            "(`deck*`, `magsnd*`, `magvid*`, `statwin*`) are skipped.", ""]
    out += table(map_hits) if map_hits else ["None."]
    out += ["", f"## Old names used in scripts without the address: {len(mentions)} lines", "",
            "Old names from the doc (Ghidra defaults excluded) that a script uses on a line without the registry "
            "address. A rename keyed by name, or a hard-coded call, could apply them again.", "",
            "| File:line | Old name | Registry | Line |", "|---|---|---|---|"]
    for path, n, old, rs, text in mentions:
        regs = "; ".join(f"{r['program']} `{reg.fmt_addr(r['address'])}` `{r['name']}`" for r in rs)
        text = text.replace("|", "\\|")
        if len(text) > 140:
            text = text[:137] + "..."
        out.append(f"| `{path}:{n}` | `{old}` | {regs} | `{text}` |")
    if not mentions:
        out.append("| | none | | |")
    return "\n".join(out) + "\n", script_hits, map_hits, mentions


def main():
    rows = attach_old_names(reg.read_registry())
    dup_md, total = render_duplicates(rows)
    with open(DUPLICATES_MD, "w", encoding="utf-8") as f:
        f.write(dup_md)
    gen_md, script_hits, map_hits, mentions = render_generators(rows)
    with open(GENERATORS_MD, "w", encoding="utf-8") as f:
        f.write(gen_md)
    print(f"{total} shared function names -> {os.path.relpath(DUPLICATES_MD, reg.REPO)}")
    print(f"{len(script_hits)} script lines, {len(map_hits)} map lines, {len(mentions)} old-name mentions "
          f"-> {os.path.relpath(GENERATORS_MD, reg.REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
