#!/usr/bin/env python3
"""Build tools/registry/verified_names.csv from the tables in docs/SYMBOL_VERIFICATION.md.

Also writes tools/registry/parse_report.md: the tables that assign no names (skipped), the rows that
could not be read, and addresses of functions and globals the doc mentions outside the name tables
that are not in the registry.

    python3 tools/registry/build_registry.py            # rewrite both files
    python3 tools/registry/build_registry.py --check    # exit 1 if either file is out of date
"""

import argparse
import os
import re
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import registry as reg  # noqa: E402

REPORT = os.path.join(reg.HERE, "parse_report.md")
ANY_ADDR_RE = re.compile(r"(?<![0-9A-Za-z_])0x([0-9a-fA-F]{5,8})(?![0-9a-fA-F])")


def build():
    rows, problems, skipped = reg.parse_doc()
    rows = reg.assign_kinds(rows, problems)
    return rows, problems, skipped


def unregistered_mentions(rows, skipped):
    """Addresses of functions or globals mentioned in prose or skipped tables but not registered."""
    registered = {(r["program"], r["address"]) for r in rows}
    index = {p: reg.read_function_index(p) for p in reg.PROGRAMS}
    globals_map = reg.read_globals_map()
    symbols = {p: reg.read_symbols(p) for p in reg.PROGRAMS}
    _, prose = reg.read_doc()
    texts = [(n, line, section) for n, line, section in prose]
    for t in skipped:
        for n, cells in t.rows:
            texts.append((n, " | ".join(cells), t.section))
    found = {}
    for n, text, section in texts:
        for m in ANY_ADDR_RE.finditer(text):
            a = int(m.group(1), 16)
            hits = []
            for p in reg.PROGRAMS:
                if (p, a) in registered:
                    continue
                if a in index[p]:
                    hits.append((p, "function", "/".join(index[p][a]), ""))
                elif a in symbols[p] and not any(n.startswith(("LAB_", "IMAGE_")) for n in symbols[p][a]):
                    name = "/".join(symbols[p][a])
                    extra = f" (engine_globals_map: `{globals_map[a]}`)" if globals_map.get(a, name) != name else ""
                    hits.append((p, "global", name, extra))
            if not hits or any((p, a) in registered for p in reg.PROGRAMS):
                continue
            entry = found.setdefault(a, {"hits": hits, "lines": [], "section": section,
                                         "snippet": text.strip()})
            entry["lines"].append(n)
    return found


def render_report(rows, problems, skipped, mentions):
    out = ["# Registry parse report", "",
           "Generated by `build_registry.py` from `docs/SYMBOL_VERIFICATION.md`; do not edit by hand.", "",
           f"{len(rows)} registry rows "
           f"({sum(r['program'] == 'MAGIC' for r in rows)} MAGIC, {sum(r['program'] == 'DUEL' for r in rows)} DUEL; "
           f"{sum(r['kind'] == 'function' for r in rows)} functions, {sum(r['kind'] == 'global' for r in rows)} globals).",
           "", "## Rows that could not be parsed", ""]
    out += [f"- {p}" for p in problems] or ["None."]
    out += ["", "## Tables that assign no names (skipped)", "",
            "These record observations (traces, step codes, bit meanings), not address-to-name claims.", "",
            "| Line | Section | Columns |", "|---|---|---|"]
    for t in skipped:
        out.append(f"| {t.line} | {t.section} | {' / '.join(h.replace('|', '/') for h in t.header)} |")
    out += ["", "## Named addresses mentioned outside the name tables", "",
            "Addresses in prose or in skipped tables that are a function start or a known global in one of the "
            "programs but have no registry row. Some are verified names that only the prose records; others are "
            "call sites, callers or unnamed functions. The program is a guess from which index has the address: "
            "every program loads at `0x00400000`, so the same address can be two different things.", "",
            "| Address | Program: kind, current name | Doc lines | Section |", "|---|---|---|---|"]
    for a in sorted(mentions):
        e = mentions[a]
        hits = "; ".join(f"{p}: {k}, `{nm}`{extra}" for p, k, nm, extra in e["hits"])
        lines = ", ".join(str(n) for n in sorted(set(e["lines"])))
        out.append(f"| `{reg.fmt_addr(a)}` | {hits} | {lines} | {e['section']} |")
    if not mentions:
        out.append("| | none | | |")
    return "\n".join(out) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="only check that the outputs are up to date")
    args = ap.parse_args(argv)
    rows, problems, skipped = build()
    report = render_report(rows, problems, skipped, unregistered_mentions(rows, skipped))
    if args.check:
        with tempfile.TemporaryDirectory() as d:
            tmp = os.path.join(d, "v.csv")
            reg.write_registry(rows, tmp)
            stale = []
            with open(tmp) as a, open(reg.REGISTRY_CSV) as b:
                if a.read() != b.read():
                    stale.append(reg.REGISTRY_CSV)
            with open(REPORT) as b:
                if b.read() != report:
                    stale.append(REPORT)
        for s in stale:
            print(f"out of date: {os.path.relpath(s, reg.REPO)} (run build_registry.py)")
        return 1 if stale else 0
    reg.write_registry(rows)
    with open(REPORT, "w", encoding="utf-8") as f:
        f.write(report)
    print(f"{len(rows)} rows -> {os.path.relpath(reg.REGISTRY_CSV, reg.REPO)}; "
          f"{len(problems)} unparsed rows, {len(skipped)} tables without names -> "
          f"{os.path.relpath(REPORT, reg.REPO)}")
    for p in problems:
        print("  unparsed:", p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
