#!/usr/bin/env python3
"""
build_glue_metadata.py - Build full dictionary of 251 glue functions with names, STE comments, and classifications.
"""

import json
import csv

METADATA = {
    # Group 1: Timer
    "004cd63b": ("Timer_InitVxD", "Initialize high precision timer via MPStime VXD driver.", ["Verify if VXD device handle is already open.", "Call CreateFileA on MPStime VXD path if not open.", "Execute DeviceIoControl code 1 to initialize timer.", "Return success status."]),
    "004cd6e3": ("Timer_GetTicks", "Query high precision hardware timer ticks.", ["Execute DeviceIoControl code 2 on VXD handle.", "Return 32-bit hardware tick counter."]),
    "004cd715": ("Timer_MarkStart", "Record baseline timestamp for performance profiling.", ["Read current hardware timer ticks.", "Store timestamp in start timestamp global."]),
    "004cd72a": ("Timer_GetElapsedFraction", "Compute percentage of elapsed time against reference interval.", ["Read current timer ticks.", "Calculate elapsed delta from baseline.", "Compute scaled percentage value."]),

    # Group 2: Spell Chain / Stack UI
    "004cd760": ("SpellChain_RegisterClass", "Register window classes and load background PIC assets for spell stack.", ["Register main spell chain and minimized window classes.", "Load spell chain PIC background illustrations.", "Create pens and solid brushes for UI chrome.", "Return initialization success status."]),
    "004cda01": ("SpellChain_CleanupUI", "Destroy menus, bitmaps, pens, and brushes used by spell chain window.", ["Destroy popup context menu.", "Free loaded PIC background objects.", "Delete GDI pens and brushes."]),
    "004cdb4f": ("SpellChain_WndProc", "Main window procedure for spell chain resolution stack.", ["Handle WM_CREATE to configure scrollbars and child card controls.", "Handle WM_PAINT to draw spell stack background and chain links.", "Handle WM_COMMAND for minimize, help, and popup menu actions.", "Forward unhandled messages to DefWindowProcA."]),
    "004cf8b6": ("SpellChain_GetCardCount", "Get number of active spell cards currently on resolution stack.", ["Query window extra bytes for spell stack count.", "Return active spell count."]),
    "004cf965": ("SpellChain_UpdateTargetPositions", "Update target coordinates and scroll offsets for cards in spell stack.", ["Iterate through all cards on resolution stack.", "Calculate child window positions and update window handles.", "Refresh scroll range if stack exceeds visible bounds."]),
    "004cfab2": ("SpellChain_HasActiveSpells", "Check if spell resolution stack has pending spells.", ["Read active spell counter.", "Return true if count is greater than zero."]),
    "004cfb2f": ("SpellChain_CreateCardSlot", "Allocate and attach card window slot to spell stack chain.", ["Create child card window control.", "Store spell card index and target index in slot array.", "Trigger layout recalculation."]),
    "004cfd68": ("SpellChain_RemoveCardSlot", "Remove card window slot from spell stack chain and destroy handle.", ["Destroy child window control.", "Shift remaining slots left in slot table.", "Invalidate window client area."]),
    "004cfe4d": ("SpellChain_CreateTargetSlot", "Create target line link between spell card and targeted permanent.", ["Create child target window control.", "Store targeting relationship coordinates in slot buffer."]),
    "004cffda": ("SpellChain_UpdateLayout", "Recalculate layout and resize spell chain window dimensions.", ["Compute required dimensions based on active spell count.", "Resize and reposition window via MoveWindow.", "Force synchronous window update."]),
    "004d05e8": ("SpellChain_SetWindowRect", "Copy and apply rectangle bounds to spell chain window.", ["Copy rectangle structure to internal bounds cache."]),
    "004d0602": ("SpellChain_MinimizedWndProc", "Window procedure for minimized spell chain icon.", ["Handle WM_PAINT to render minimized spell icon.", "Handle WM_RBUTTONUP / WM_LBUTTONDBLCLK to restore full spell chain.", "Handle popup menu commands."]),
    "004d0965": ("SpellChain_IsVisible", "Query visibility status of spell chain window.", ["Test window visibility flag and return boolean status."]),
    "004d09bd": ("SpellChain_IsMinimized", "Query minimized status of spell chain window.", ["Test minimized window visibility and return boolean status."]),
    "004d0a30": ("SpellChain_GetActiveCount", "Get active spell counter.", ["Return active spell counter register."]),
    "004d0a42": ("SpellChain_ProcessTriggerEvent", "Dispatch spell chain resolution trigger event to active permanents.", ["Format trigger event parameters.", "Notify card scripts of pending resolution."]),

    # Group 3: Card Rules Scripts & Abilities
    "004d0cdb": ("Card_PrismaticDragon_ColorChange", "Execute Prismatic Dragon (Astral set) upkeep color change ability.", ["Choose random replacement color at upkeep.", "Apply new color mask to creature slot.", "Trigger card refresh event."]),
    "004d109a": ("Card_RainbowKnights_ActivatedAbility", "Execute Rainbow Knights (Astral set) activated abilities and random protection.", ["On cast: select random color and grant protection from that color.", "Option 1 (pay RR): add random power bonus (+0 to +2) until end of turn.", "Option 2 (pay W): grant first strike until end of turn.", "Option 3: cancel activation."]),
    "004d1cc4": ("Card_Sinbad_Draw", "Execute Sinbad card draw ability.", ["Draw top card from active library.", "Reveal drawn card and verify if land.", "Discard card if not a land, or put into hand."]),
    "004d1e10": ("Card_Kudzu_LandDestruction", "Process Kudzu land destruction and transfer trigger.", ["Trigger destruction of enchanted land.", "Prompt controller to attach Kudzu to opponent land."]),
    "004d212c": ("Card_BronzeTablets_AnteSwap", "Execute Bronze Tablets ante swap ability.", ["Prompt target player (Swap cards, lose 10 life, or concede).", "Execute chosen ante swap or life loss effect."]),
    "004d2610": ("Card_XenicPoltergeist_AnimateArtifact", "Execute Xenic Poltergeist ability to animate artifact into creature.", ["Validate noncreature artifact target.", "Set power and toughness equal to converted mana cost.", "Grant creature type until end of turn."]),
    "004d29da": ("Card_VesuvanDoppelganger_Copy", "Copy target creature on battlefield as Vesuvan Doppelganger.", ["Validate chosen creature target.", "Copy power, toughness, colors, and abilities.", "Retain original blue color identity."]),
    "004d2c17": ("Card_VesuvanDoppelganger_Upkeep", "Prompt player at upkeep to choose a new Doppelganger mimic target.", ["Display prompt asking to switch copied creature.", "Re-execute copy routine if player approves."]),
    "004d2d28": ("Card_Doppelganger_ClearMimic", "Clear copied attributes when Doppelganger leaves play.", ["Reset overridden stats to base Doppelganger card stats."]),
    "004d2e2a": ("Card_Doppelganger_ApplyMimicStats", "Apply copied stats and abilities to Doppelganger slot.", ["Copy base power and toughness from source creature."]),
    "004d2f6c": ("Card_Doppelganger_SyncAbilities", "Synchronize active keyword abilities with copied creature.", ["Copy flying, first strike, trample, and protection flags."]),
    "004d30ae": ("Card_Doppelganger_CheckState", "Validate Doppelganger mimic state integrity.", ["Check if copied creature reference remains valid."]),
    "004d3144": ("Card_IslandSanctuary_SkipDraw", "Skip draw step to activate Island Sanctuary combat barrier.", ["Set flag to skip regular draw step."]),
    "004d31a9": ("Card_IslandSanctuary_AttackRestriction", "Apply attack restriction preventing non-flying/islandwalk attackers.", ["Check attacker abilities against Island Sanctuary restriction."]),
    "004d3229": ("Card_IslandSanctuary_Trigger", "Trigger Island Sanctuary upkeep choice.", ["Prompt controller to activate protection effect."]),
    "004d328c": ("Card_IslandSanctuary_CheckActive", "Check if Island Sanctuary protection is active this turn.", ["Return active state flag."]),
    "004d332a": ("Card_IslandSanctuary_Prompt", "Display Island Sanctuary activation prompt.", ["Load prompt text and query player decision."]),
    "004d353d": ("Card_LivingLands_AnimateForests", "Apply Living Lands continuous effect making Forests 1/1 creatures.", ["Iterate all lands in play.", "Set Forest permanents to 1/1 creatures."]),
    "004d374d": ("Card_KormusBell_AnimateSwamps", "Apply Kormus Bell continuous effect making Swamps 1/1 creatures.", ["Iterate all lands in play.", "Set Swamp permanents to 1/1 creatures."]),
    "004d395d": ("Card_TitaniasSong_AnimateArtifacts", "Apply Titania's Song continuous effect animating noncreature artifacts.", ["Iterate artifacts in play.", "Set power/toughness equal to casting cost.", "Remove noncreature artifact abilities."]),
    "004d3d1d": ("Card_TitaniasSong_RemoveAbilities", "Disable native abilities of artifacts animated by Titania's Song.", ["Clear ability bitmask flags."]),
    "004d3d82": ("Card_TitaniasSong_RestoreAbilities", "Restore native abilities of artifacts when Titania's Song leaves.", ["Re-enable original ability flags."]),
    "004d3dff": ("Card_TitaniasSong_UpdateStatus", "Refresh active status of animated artifacts.", ["Re-evaluate active artifact list."]),
    "004d3fa1": ("Card_TitaniasSong_ClearFlags", "Clear continuous animation flags.", ["Reset artifact status markers."]),
    "004d4099": ("Card_TitaniasSong_CheckTrigger", "Check if Titania's Song should trigger upon artifact entering play.", ["Evaluate newly entered permanent."]),
    "004d420e": ("Card_PersonalIncarnation_RedirectDamage", "Execute Personal Incarnation damage redirection ability.", ["Prompt controller for amount of damage to redirect.", "Redirect chosen damage to Personal Incarnation."]),
    "004d4762": ("Card_AliFromCairo_PreventLethalDamage", "Execute Ali from Cairo damage prevention preventing life from dropping below 1.", ["Check incoming lethal combat or spell damage.", "Reduce damage such that player life remains at least 1.", "Log prevention message."]),
    "004d4d1f": ("Card_AliFromCairo_ResetState", "Reset Ali from Cairo prevention tracking at end of turn.", ["Clear turn damage counters."]),
    "004d4f73": ("Card_ShivanDragon_PumpFirebreathing", "Activate Shivan Dragon firebreathing (+1/+0 for R).", ["Pay R mana cost.", "Add +1 power boost until end of turn."]),
    "004d5626": ("Card_DragonWhelp_PumpFirebreathing", "Activate Dragon Whelp firebreathing (+1/+0 for R).", ["Pay R mana cost.", "Increment pump counter.", "Add +1 power boost until end of turn."]),
    "004d5c1e": ("Card_DragonWhelp_EndTurnCheck", "Destroy Dragon Whelp at end of turn if pumped more than twice.", ["Check pump counter.", "Destroy Dragon Whelp if counter exceeds 2."]),
    "004d6391": ("Card_FrozenShade_ClearBoost", "Clear Frozen Shade power and toughness boost at cleanup.", ["Reset temporary power/toughness buffs."]),
    "004d6400": ("Card_FrozenShade_PumpBlack", "Activate Frozen Shade pump ability (+1/+1 for B).", ["Pay B mana cost.", "Add +1/+1 buff until end of turn."]),
    "004d6706": ("Card_WaterElemental_PumpBlue", "Activate Water Elemental pump ability (+1/-1 for U).", ["Pay U mana cost.", "Modify power and toughness."]),
    "004d683f": ("Card_ClockworkBeast_ResetCounters", "Initialize +1/+0 counters on Clockwork Beast.", ["Set +1/+0 counters to 7 upon entering play."]),
    "004d6ad4": ("Card_ClockworkBeast_CombatTrigger", "Deduct counter from Clockwork Beast after attacking or blocking.", ["Deduct 1 counter at end of combat."]),
    "004d6c43": ("Card_ClockworkBeast_Rewind", "Pay mana during upkeep to wind up Clockwork Beast counters.", ["Prompt player to pay mana to restore +1/+0 counters."]),
    "004d6d82": ("Card_ClockworkBeast_GetPower", "Calculate effective power of Clockwork Beast.", ["Return base power plus active counter count."]),
    "004d6e79": ("Card_ClockworkBeast_GetToughness", "Calculate effective toughness of Clockwork Beast.", ["Return base toughness plus active counter count."]),
    "004d7065": ("Card_GaeasLiege_TransformLand", "Transform target land into Forest with Gaea's Liege.", ["Validate chosen target land.", "Override land type to Forest until Gaea's Liege leaves."]),
    "004d7724": ("Card_GaeasLiege_ResetLand", "Revert transformed lands when Gaea's Liege leaves play.", ["Restore original land types."]),
    "004d777b": ("Card_GaeasLiege_CheckAttackRestriction", "Verify if defending player controls a Forest before attacking.", ["Check defending player land types."]),
    "004d788d": ("Card_GaeasLiege_IsForest", "Test if target card is a Forest.", ["Check land subtype."]),
    "004d78d2": ("Card_GaeasLiege_CombatCheck", "Evaluate combat viability for Gaea's Liege.", ["Return combat suitability score."]),
    "004d79a6": ("Card_SedgeTroll_CheckSwamp", "Check if controller controls a Swamp for Sedge Troll +1/+1 buff.", ["Query player land list for Swamps."]),
    "004d7a1b": ("Card_SedgeTroll_Regenerate", "Activate Sedge Troll regeneration ability (pay B).", ["Pay B mana cost.", "Apply regeneration shield to Sedge Troll."]),
    "004d7b68": ("Card_LivingWall_PromptRegenerate", "Prompt controller to regenerate Living Wall.", ["Query player decision to pay regeneration cost."]),
    "004d7bb5": ("Card_LivingWall_Regenerate", "Activate Living Wall regeneration ability (pay 1).", ["Pay 1 mana cost.", "Apply regeneration shield."]),
    "004d7c60": ("Card_GenericCreature_Regenerate", "Apply generic regeneration shield to creature.", ["Validate mana payment.", "Set STATUS_REGENERATED flag on card slot."]),
    "004d7e90": ("Card_GenericCreature_CanRegenerate", "Check if creature can activate its regeneration ability.", ["Check mana availability and tapped state."]),
    "004d80d3": ("Card_GenericCreature_TriggerRegen", "Trigger creature regeneration during fatal damage resolution.", ["Consume regeneration shield, tap creature, and remove from combat."]),
    "004d817b": ("Card_DrudgeSkeletons_Regenerate", "Activate Drudge Skeletons regeneration ability (pay B).", ["Pay B mana cost.", "Apply regeneration shield."]),
    "004d87cb": ("Card_UthdenTroll_Regenerate", "Activate Uthden Troll regeneration ability (pay R).", ["Pay R mana cost.", "Apply regeneration shield."]),
    "004d8e4c": ("Card_WillOTheWisp_Regenerate", "Activate Will-o'-the-Wisp regeneration ability (pay B).", ["Pay B mana cost.", "Apply regeneration shield."]),
    "004d94e1": ("Card_MarrowThieves_Regenerate", "Activate Marrow Thieves regeneration ability.", ["Sacrifice creature to apply regeneration shield."]),
    "004d9afd": ("Card_HypnoticSpecter_RandomDiscard", "Force defending player to discard a random card on combat damage.", ["Verify unblocked combat damage dealt to opponent.", "Select random card from opponent hand.", "Move card to opponent graveyard."]),
    "004d9f7e": ("Card_TimeElemental_BouncePermanent", "Activate Time Elemental ability to return permanent to hand.", ["Validate target permanent.", "Return permanent to owner hand.", "Deal 5 damage to Time Elemental controller."]),
    "004da482": ("Card_NorthernPaladin_DestroyBlack", "Activate Northern Paladin ability to destroy target black permanent.", ["Validate target black permanent.", "Destroy target permanent."]),
    "004da858": ("Card_RoyalAssassin_DestroyTapped", "Activate Royal Assassin ability to destroy target tapped creature.", ["Validate target tapped creature.", "Destroy target creature."]),
    "004daa50": ("Card_DwarvenDemolitionTeam_DestroyWall", "Activate Dwarven Demolition Team ability to destroy target Wall.", ["Validate target Wall creature.", "Destroy target Wall."]),
    "004dac11": ("Card_KingSuleiman_DestroyDjinn", "Activate King Suleiman ability to destroy target Djinn or Efreet.", ["Validate target Djinn or Efreet creature.", "Destroy target creature."]),
    "004dae76": ("Card_Targeting_PromptCreature", "Prompt player to select creature target for activated ability.", ["Display creature target selector.", "Return chosen target slot index."]),
    "004db024": ("Card_NettlingImp_ForceAttack", "Activate Nettling Imp ability to force creature to attack.", ["Validate target non-Wall creature.", "Set forced attack flag on target creature."]),
    "004db401": ("Card_NettlingImp_CheckEndTurn", "Destroy creature forced by Nettling Imp if it failed to attack.", ["Check if creature attacked during turn.", "Destroy creature if it did not attack."]),
    "004db8c9": ("Card_NettlingImp_IsTargetEligible", "Validate if creature is eligible for Nettling Imp targeting.", ["Verify creature is controlled by active turn player and is not a Wall."]),
    "004dba1c": ("Card_SorceressQueen_SetStats02", "Activate Sorceress Queen ability to set creature stats to 0/2.", ["Validate target creature.", "Set target power to 0 and toughness to 2 until end of turn."]),
    "004dbfdb": ("Card_SorceressQueen_ResetStats", "Reset creature stats modified by Sorceress Queen at cleanup.", ["Restore original base power and toughness."]),
    "004dc2ca": ("Card_StoneGiant_Fling", "Activate Stone Giant ability to grant flying to smaller creature.", ["Validate creature target with toughness less than Stone Giant power.", "Grant flying until end of turn.", "Destroy target creature at end of turn."]),
    "004dc6c7": ("Card_DwarvenWarriors_MakeUnblockable", "Activate Dwarven Warriors ability making creature unblockable.", ["Validate creature target with power 2 or less.", "Set unblockable flag until end of turn."]),
    "004dc9ed": ("Card_CavePeople_Mountainwalk", "Activate Cave People ability granting mountainwalk.", ["Pay activation cost.", "Grant mountainwalk until end of turn."]),
    "004dce51": ("Card_PradeshGypsies_PreventAttack", "Activate Pradesh Gypsies ability preventing creature from attacking.", ["Pay activation cost and tap target creature.", "Prevent target creature from attacking this turn."]),
    "004dd33b": ("Card_PradeshGypsies_ResetRestriction", "Clear attack restriction applied by Pradesh Gypsies at end of turn.", ["Reset attack restriction flag."]),
    "004dd632": ("Card_SamiteHealer_PreventDamage", "Activate Samite Healer ability to prevent 1 damage.", ["Validate target creature or player.", "Apply 1 point damage prevention shield."]),
    "004dd98f": ("Card_SamiteHealer_CalculateHealAdvantage", "Calculate AI tactical heuristic for Samite Healer prevention.", ["Evaluate damage on friendly creatures and player life."]),
    "004ddcf4": ("Card_AlabasterPotion_HealOrPrevent", "Execute Alabaster Potion spell (gain X life or prevent X damage).", ["Prompt player for life gain or damage prevention mode.", "Apply life gain or damage prevention shield."]),
    "004dde51": ("Card_HealingSalve_DamagePrevention", "Process Healing Salve damage prevention shield.", ["Deduct incoming damage from active prevention pool."]),
    "004ddefa": ("Card_DamagePrevention_ApplyBubble", "Add damage prevention bubble to card slot.", ["Increment prevention counter."]),
    "004ddf4b": ("Card_DamagePrevention_ReduceDamage", "Deduct prevented damage from incoming damage payload.", ["Calculate reduced damage amount."]),
    "004ddf98": ("Card_DamagePrevention_ClearAtCleanup", "Clear remaining damage prevention shields at cleanup.", ["Reset prevention counters to zero."]),
    "004de05f": ("Card_DamagePrevention_QueryAmount", "Query active damage prevention capacity on target.", ["Return available prevention points."]),
    "004de0b3": ("Card_DamagePrevention_PromptTarget", "Prompt player for damage prevention target.", ["Display target selector dialog."]),
    "004de100": ("Card_DamagePrevention_CheckSource", "Validate damage source for prevention effect.", ["Verify source damage validity."]),
    "004de1c0": ("Card_ErgRaiders_UpkeepDamage", "Deal 2 damage to controller if Erg Raiders did not attack.", ["Check if Erg Raiders attacked last turn.", "Deal 2 damage to controller if no attack occurred."]),
    "004de35e": ("Card_ErgRaiders_MarkAttack", "Mark Erg Raiders as having attacked this turn.", ["Set attacked flag on card slot."]),
    "004de492": ("Card_ErgRaiders_ClearTurnAttack", "Reset Erg Raiders turn attack state at untap.", ["Clear attacked flag."]),
    "004de83d": ("Card_Leviathan_SacrificeLands", "Process Leviathan upkeep requirement (sacrifice two Islands or remain tapped).", ["Prompt controller to sacrifice two Islands.", "Sacrifice Islands or keep Leviathan tapped."]),
    "004dec09": ("Card_Leviathan_PromptLandSacrifice", "Display land sacrifice selection dialog for Leviathan.", ["Prompt player to select two Islands to sacrifice."]),
    "004dee6b": ("Card_Leviathan_SelectLand", "Handle individual land selection for Leviathan sacrifice.", ["Move selected land to graveyard."]),
    "004defc2": ("Card_Leviathan_AttackTrigger", "Require sacrifice of two Islands when Leviathan attacks.", ["Process attack declaration land sacrifice."]),
    "004df04a": ("Card_BrothersOfFire_Ping", "Activate Brothers of Fire ability (deal 1 damage to target and 1 to self).", ["Validate target creature or player.", "Deal 1 damage to target.", "Deal 1 damage to Brothers of Fire controller."]),
    "004df20c": ("Card_BrothersOfFire_EvaluateTarget", "Calculate AI tactical score for Brothers of Fire activation.", ["Evaluate board advantage of pinging target."]),
    "004df314": ("Card_CrimsonManticore_DamageTarget", "Activate Crimson Manticore ability (deal 1 damage to attacking/blocking creature).", ["Validate target combat creature.", "Deal 1 damage to target."]),
    "004df678": ("Card_ProdigalSorcerer_PingTarget", "Activate Prodigal Sorcerer ability (deal 1 damage to target).", ["Validate target creature or player.", "Deal 1 damage to target."]),
    "004df8ba": ("Card_DirectDamage_EvaluateBestTarget", "AI heuristic to find highest priority direct damage target.", ["Iterate enemy creatures and player.", "Return highest tactical value target."]),
    "004dfb23": ("Card_DirectDamage_PromptAndDealDamage", "Prompt player for direct damage target and execute damage.", ["Display target selector.", "Apply damage to chosen target."]),
    "004dfd39": ("Card_PirateShip_PingTarget", "Activate Pirate Ship ability (deal 1 damage to target).", ["Verify Pirate Ship is not summoning sick.", "Deal 1 damage to target creature or player."]),
    "004dfe94": ("Card_PirateShip_CheckIslandwalk", "Check if Pirate Ship can attack defending player.", ["Verify defending player controls an Island."]),
    "004dff88": ("Card_PirateShip_HasIsland", "Check if controller controls an Island for Pirate Ship survival.", ["Query controller lands for Islands."]),
    "004e0037": ("Card_PirateShip_AttackTrigger", "Destroy Pirate Ship if controller controls no Islands.", ["Destroy card if no Island is in play."]),
    "004e00e7": ("Card_IslandFishJasconius_PayToUntap", "Process Island Fish Jasconius upkeep (pay UUU to untap).", ["Prompt player to pay UUU.", "Untap creature if paid."]),
    "004e03b5": ("Card_IslandFishJasconius_CheckIslands", "Check if defending player controls an Island for attack eligibility.", ["Verify defender Island presence."]),
    "004e04be": ("Card_IslandFishJasconius_DestroyIfNoIslands", "Destroy Island Fish Jasconius if controller has no Islands.", ["Destroy card if no Island remains."]),
    "004e0580": ("Card_RodOfRuin_Ping", "Activate Rod of Ruin ability (pay 3, tap: deal 1 damage).", ["Pay 3 mana cost.", "Deal 1 damage to target creature or player."]),
    "004e07b5": ("Card_RodOfRuin_EvaluateAi", "Calculate AI tactical score for Rod of Ruin activation.", ["Evaluate target advantage."]),
    "004e08ac": ("Card_RodOfRuin_PayActivation", "Deduct mana cost for Rod of Ruin activation.", ["Deduct 3 mana from pool."]),
    "004e095b": ("Card_RodOfRuin_SelectTarget", "Select target for Rod of Ruin direct damage.", ["Display target selector."]),
    "004e0ab7": ("Card_OrcishArtillery_ShootTarget", "Activate Orcish Artillery ability (deal 2 damage to target, 3 to controller).", ["Validate target.", "Deal 2 damage to target.", "Deal 3 damage to Orcish Artillery controller."]),
    "004e0c1c": ("Card_PsionicEntity_ShootTarget", "Activate Psionic Entity ability (deal 2 damage to target, 3 to self).", ["Validate target.", "Deal 2 damage to target.", "Deal 3 damage to Psionic Entity."]),
    "004e0e60": ("Card_PsionicEntity_EvaluateTarget", "Calculate AI tactical score for Psionic Entity activation.", ["Evaluate target advantage versus self-damage."]),
    "004e0fd0": ("Card_PsionicEntity_SelfDamage", "Apply self-inflicted damage from Psionic Entity activation.", ["Deal 3 damage to Psionic Entity creature slot."]),
    "004e114e": ("Card_KhabalGhoul_AddCounterOnDeath", "Add +1/+1 counter to Khabal Ghoul when a creature dies.", ["Check if a creature died this turn.", "Add +1/+1 counter at end of turn."]),
    "004e12cf": ("Card_KhabalGhoul_CheckCreatureDeath", "Track creature death events for Khabal Ghoul.", ["Increment death counter register."]),
    "004e191d": ("Card_KhabalGhoul_ApplyCounterBonus", "Apply stats bonus from Khabal Ghoul +1/+1 counters.", ["Add counter bonus to effective power/toughness."]),
    "004e1a2b": ("Card_KhabalGhoul_ResetCounterBonus", "Reset turn counter bonus for Khabal Ghoul.", ["Clear temporary buff register."]),
    "004e1b38": ("Card_LordOfAtlantis_PayOrSacrifice", "Process Lord of Atlantis sacrifice or mana payment upkeep.", ["Prompt player for upkeep payment."]),
    "004e1c8c": ("Card_LordOfAtlantis_ApplyMerfolkBuff", "Apply Lord of Atlantis anthem (+1/+1 and islandwalk to all Merfolk).", ["Iterate Merfolk creatures and grant buff."]),
    "004e1d96": ("Card_LordOfAtlantis_RemoveMerfolkBuff", "Remove Lord of Atlantis anthem when card leaves battlefield.", ["Clear Merfolk buffs."]),
    "004e1e6c": ("Card_LordOfAtlantis_IslandwalkTrigger", "Check islandwalk attack validity for buffed Merfolk.", ["Verify defender Island presence."]),
    "004e1f0d": ("Card_LordOfAtlantis_CheckMerfolkType", "Test if target creature has Merfolk subtype.", ["Check creature subtype."]),
    "004e1fcb": ("Card_ForceOfNature_PayUpkeep", "Process Force of Nature upkeep (pay GGGG or take 8 damage).", ["Prompt controller to pay GGGG.", "Deal 8 damage to controller if unpaid."]),
    "004e2101": ("Card_ForceOfNature_AiPayOrTakeDamage", "AI decision logic for Force of Nature upkeep.", ["Evaluate available green mana versus life total."]),
    "004e22b2": ("Card_BirdsOfParadise_TapForMana", "Activate Birds of Paradise ability (tap: add one mana of any color).", ["Prompt player for chosen mana color.", "Add 1 mana of chosen color to player mana pool."]),
    "004e268e": ("Card_CosmicHorror_PayUpkeep", "Process Cosmic Horror upkeep (pay 3 mana or take 7 damage and destroy).", ["Prompt controller to pay 3 mana.", "Destroy card and deal 7 damage if unpaid."]),
    "004e2841": ("Card_LordOfThePit_SacrificeOrDamage", "Process Lord of the Pit upkeep (sacrifice creature or take 7 damage).", ["Prompt controller to sacrifice a creature.", "Deal 7 damage to controller if no creature is sacrificed."]),
    "004e2b99": ("Card_LordOfThePit_FindSacrificeCandidate", "Find eligible non-Lord creature to sacrifice.", ["Iterate controller creatures.", "Return index of lowest value sacrifice candidate."]),
    "004e2c7f": ("Card_KormusBell_PayLandUpkeep", "Process Kormus Bell / animated land upkeep cost.", ["Prompt player to pay mana or sacrifice land."]),
    "004e2fe8": ("Card_KormusBell_CheckSwampCreature", "Test if permanent is an animated Swamp creature.", ["Verify Swamp permanent type and creature status."]),
    "004e3128": ("Card_NetherShadow_CheckGraveyard", "Check if Nether Shadow can return from graveyard at upkeep.", ["Verify if at least 3 creature cards lie above Nether Shadow in graveyard."]),
    "004e3185": ("Card_NetherShadow_CountCreaturesAbove", "Count creature cards positioned above Nether Shadow in graveyard.", ["Iterate graveyard cards above Nether Shadow index."]),
    "004e32f3": ("Card_NetherShadow_ReturnFromGrave", "Return Nether Shadow from graveyard directly to battlefield.", ["Move Nether Shadow from graveyard to battlefield.", "Log resurrection announcement."]),
    "004e34e4": ("Card_RockHydra_DecrementHead", "Remove +1/+1 head counter from Rock Hydra when damaged.", ["Deduct 1 head counter per damage point."]),
    "004e3563": ("Card_RockHydra_DamageTrigger", "Process damage prevention via Rock Hydra head counter sacrifice.", ["Prevent damage by removing head counters."]),
    "004e35e4": ("Card_RockHydra_UpdateStatsFromHeads", "Update Rock Hydra power and toughness based on active head counters.", ["Set power and toughness equal to head counter count."]),
    "004e3730": ("Card_RockHydra_InitHeads", "Initialize Rock Hydra head counters upon entering play.", ["Set head counters equal to X casting cost."]),
    "004e378b": ("Card_RockHydra_RegrowHead", "Pay mana to regrow or restore Rock Hydra head counters.", ["Prompt player to pay RRR to regrow heads.", "Add head counter if paid."]),
    "004e3b55": ("Card_AliBaba_TapWall", "Activate Ali Baba ability (pay R: tap target Wall).", ["Validate target Wall creature.", "Tap target Wall."]),
    "004e3e46": ("Card_LeyDruid_UntapLand", "Activate Ley Druid ability (tap: untap target land).", ["Validate target tapped land.", "Untap target land."]),
    "004e4144": ("Card_LeyDruid_AiEvaluateLand", "Calculate AI tactical score for untapping target land.", ["Evaluate mana generation advantage."]),
    "004e42ac": ("Card_LeyDruid_ExecuteUntap", "Execute untap action on chosen land.", ["Clear STATUS_TAPPED flag on land slot."]),
    "004e4508": ("Card_HurkylsRecall_PickArtifact", "Prompt player to select target player for Hurkyl's Recall.", ["Display player target selector."]),
    "004e474e": ("Card_HurkylsRecall_ReturnAllArtifacts", "Return all artifacts owned by target player to hand.", ["Iterate all artifacts controlled by target player.", "Move artifacts to owner hand."]),
    "004e4807": ("Card_Venom_DestroyCombatBlocker", "Attach Venom aura to creature and setup combat destroy trigger.", ["Validate target creature.", "Attach Venom aura."]),
    "004e4fae": ("Card_Venom_AttachToCreature", "Assign Venom aura link to enchanted creature slot.", ["Store aura target relationship."]),
    "004e538e": ("Card_Venom_CombatDamageTrigger", "Mark combat opponents damaged by Venom creature for destruction.", ["Set pending destroy flag on combat blockers."]),
    "004e55d5": ("Card_Venom_DestroyAtEndOfCombat", "Destroy all creatures marked by Venom at end of combat.", ["Destroy marked combat creatures."]),
    "004e580d": ("Card_Venom_AiEvaluateAura", "Calculate AI tactical score for casting Venom on target creature.", ["Evaluate combat advantage."]),
    "004e592c": ("Card_Venom_AiCastScore", "Determine AI mana allocation priority for Venom.", ["Calculate casting priority."]),
    "004e5a39": ("Card_Venom_ClearAuraFlags", "Clear Venom combat tracking flags at end of turn.", ["Reset temporary combat markers."]),
    "004e5e3b": ("Card_RadjanSpirit_RemoveFlying", "Activate Radjan Spirit ability (tap: target creature loses flying).", ["Validate target creature with flying.", "Remove flying keyword flag until end of turn."]),
    "004e61a6": ("Card_HurrJackal_GrantCombatAbility", "Activate Hurr Jackal ability granting combat advantage.", ["Validate target creature.", "Apply temporary combat keyword buff."]),

    # Group 4: Card Queries & Attributes
    "004e654a": ("CardQuery_PlayerControlsColor", "Check if player controls any permanent matching the specified color mask.", ["Iterate active cards in play for player.", "Test color mask against card color table.", "Return 1 if match found, else 0."]),
    "004e65e1": ("CardQuery_ForEachPermanent", "Iterate active battlefield cards and invoke callback on each permanent.", ["Iterate players and active card slots.", "Execute callback function on each valid card slot."]),
    "004e66b3": ("Card_IncrementCounter", "Increment counter on card slot and notify state machine.", ["Increment slot counter register.", "Trigger upkeep notification if not AI simulation."]),
    "004e676b": ("Card_DecrementCounter", "Decrement counter on card slot.", ["Decrement slot counter register."]),
    "004e67e1": ("Card_AddCounters", "Add specified count of counters to card slot.", ["Add delta to slot counter register.", "Trigger state machine update."]),
    "004e689b": ("Card_RemoveCounters", "Deduct specified count of counters from card slot.", ["Subtract delta from counter register."]),
    "004e6913": ("Card_SetCounters", "Set absolute counter value on card slot (clamped to 255).", ["Clamp count to 0xFF.", "Write value to slot counter register."]),
    "004e6978": ("Card_GetCounters", "Read counter count from card slot.", ["Return 8-bit counter value from card slot."]),
    "004e69ac": ("CardTarget_PromptTargetCreature", "Display target selector for creature permanents.", ["Invoke target selection dialog with creature filter.", "Store chosen target in target buffer."]),
    "004e6add": ("CardTarget_SetTargetCreature", "Assign targeted creature to card slot target buffer.", ["Validate target and assign target index."]),
    "004e6bff": ("CardTarget_HasValidCreatureTarget", "Validate whether valid creature target exists for action.", ["Check available creatures matching criteria."]),
    "004e6dcc": ("CardTarget_PromptTargetPermanent", "Display target selector for any permanent.", ["Invoke target selection dialog with permanent filter."]),
    "004e6efd": ("CardTarget_SetTargetPermanent", "Assign targeted permanent to slot buffer.", ["Validate and store permanent target."]),
    "004e701f": ("CardTarget_HasValidPermanentTarget", "Validate permanent target availability.", ["Check available permanents matching filter."]),
    "004e70ad": ("CardTarget_PromptTargetPlayerOrCreature", "Display target selector for player or creature.", ["Invoke target selector allowing player or creature targets."]),
    "004e71de": ("CardTarget_SetTargetPlayerOrCreature", "Assign player or creature target to slot buffer.", ["Validate and store chosen target."]),
    "004e7300": ("CardTarget_HasValidPlayerOrCreatureTarget", "Validate player or creature target availability.", ["Check available targets matching criteria."]),

    # Group 5: Adventure Mode & Audio Events
    "004e73a0": ("Adventure_EnterTownLocation", "Initialize town interface, load dialog pic assets, and configure display.", ["Load advfac64.pic, advinter800.pic, and dbox.spr.", "Initialize town UI buttons and layout.", "Display town backdrop."]),
    "004e7936": ("Adventure_PromptLocationMenu", "Display overworld location menu options (Save, Quit, Deck, etc.).", ["Render location options dialog.", "Prompt user for selection."]),
    "004e7a6f": ("Adventure_HandleLocationMenuChoice", "Process selected menu action in overworld location.", ["Handle Save Game, Edit Deck, or Leave Location."]),
    "004e7da1": ("Adventure_ExitTownLocation", "Cleanup location state and return to world map.", ["Free location UI resources.", "Restore world map state."]),
    "004e7f51": ("Adventure_PlayLocationMusic", "Manage location background music playback based on terrain and castle color.", ["Determine music track for current location.", "Stream WAV music track from sound archive."]),
    "004e93df": ("Adventure_UpdateWorldMapLoop", "Main overworld turn processing, player movement, and enemy wizard AI pathing.", ["Process player input coordinates.", "Update enemy wizard positions across Shandalar map.", "Check for wandering monster encounters."]),
    "004ea7a6": ("Adventure_GetLocationEncounterIndex", "Retrieve encounter table entry for current coordinate.", ["Return encounter index for map tile."]),
    "004ea8df": ("Adventure_SetLocationEncounterIndex", "Store encounter index for map coordinate.", ["Write encounter index to coordinate map."]),
    "004ea97c": ("Adventure_CheckMonsterEncounter", "Test if enemy monster intercepts player on world map.", ["Calculate distance between player and monster sprites.", "Trigger encounter if collision detected."]),
    "004eaa19": ("Adventure_FormatNewsString", "Format news broadcast text buffer.", ["Copy news headline into news string buffer."]),
    "004eaa9c": ("Adventure_AppendNewsDetails", "Concatenate encounter details to news buffer.", ["Append monster and town names to news text."]),
    "004eabb2": ("Adventure_PlayMonsterEncounterSound", "Play audio cue for wandering monster.", ["Identify monster creature type.", "Play corresponding monster sound effect WAV."]),
    "004ead33": ("Adventure_TriggerDuelFromEncounter", "Transition from overworld encounter into duel arena.", ["Initialize duel parameters.", "Launch tactical duel engine."]),
    "004ead96": ("Adventure_ReloadWorldPalette", "Restore overworld 8-bit palette.", ["Apply default world map palette."]),
    "004eadb7": ("Adventure_LoadFacePalette", "Load 64-color character portrait palette.", ["Load advfac64.pic palette colors into GDI palette."]),
    "004eade5": ("Adventure_NewsFlash_EnemyAttack", "Broadcast news alert: enemy wizard sends creature to attack town.", ["Load newsback.pic and play newsflash.wav.", "Display animated news banner announcing attack."]),
    "004eb2f9": ("Adventure_NewsFlash_Retaliation", "Broadcast news alert: retaliation attack against player town.", ["Display news banner announcing retaliation raid."]),
    "004eb824": ("Adventure_NewsFlash_DominionSpell", "Broadcast news alert: wizard casts Spell of Dominion.", ["Display warning that enemy wizard is casting Dominion spell.", "Display mana taps remaining."]),
    "004ebcdc": ("Adventure_Audio_PlayEffect", "Play sound effect with voice channel allocation.", ["Allocate audio channel.", "Stream WAV audio data."]),
    "004ebd62": ("Adventure_Audio_PlayEffectAtVolume", "Play sound effect at specified volume level.", ["Set volume gain and play sound effect."]),
    "004ebdca": ("Adventure_Audio_PlayEffectLooped", "Play looped ambient sound effect.", ["Configure sound track for continuous looping."]),
    "004ebe1a": ("Adventure_Audio_StopEffectChannel", "Stop specific audio effect channel.", ["Halt playback on audio channel."]),
    "004ebe61": ("Adventure_Audio_SetPlaybackPosition", "Set sound track marker offset.", ["Seek to position in audio stream."]),
    "004ebebf": ("Adventure_Audio_StopAllTracks", "Stop all digital audio streaming channels.", ["Stop all active WAV playback."]),
    "004ebeeb": ("Adventure_Audio_PlayCastleVictory", "Play castle victory fanfare.", ["Play castle victory WAV corresponding to castle color."]),
    "004ebfef": ("Adventure_Audio_PlayDuelIntro", "Play duel intro fanfare.", ["Play dueltune.wav audio track."]),
    "004ec055": ("Adventure_Audio_PlayTerrainAmbience", "Play ambient biome sound effects and bird calls.", ["Select ambient WAV based on terrain biome (plains, forest, swamp, etc.)."]),
    "004ec32f": ("Adventure_Audio_PlayFootstep", "Play footstep walking sound effects by terrain type.", ["Play terrain-specific walking audio clip."]),
    "004ec439": ("Adventure_Audio_FindSoundOnDrives", "Search optical drive paths for streaming sound assets.", ["Iterate drive letters to find game asset directory."]),
    "004ec4fc": ("Adventure_Audio_GetMusicDrivePath", "Locate music WAV files on installation drive.", ["Return path to sound\\locmus1.wav."]),
    "004ec572": ("Adventure_Audio_FreeSoundTrack", "Free allocated sound track memory buffers.", ["Release sound track memory."]),
    "004ec5be": ("Adventure_Audio_InitSoundTrack", "Load and initialize WAV audio stream.", ["Open WAV file and initialize audio streaming buffer."]),
    "004ec65a": ("Adventure_Audio_GetTrackStatus", "Query active audio track playback state.", ["Return track status code."]),
    "004ec6ea": ("Adventure_Map_GetTerrainAtCoord", "Query map terrain tile at coordinate.", ["Read tile type from world map grid."]),
    "004ec7f9": ("Adventure_Map_RedrawViewport", "Redraw overworld campaign view area and monster sprites.", ["Blit terrain tiles and draw monster sprites."]),
    "004ec98e": ("Adventure_Map_UpdateLightingAndPalette", "Apply day/night cycle palette fade.", ["Load todpal.tr and update ambient palette lighting."]),
    "004eccd7": ("Adventure_ShowDefeatScreen", "Display Arzakon victory defeat cinematic sequence.", ["Load uth_arz.pic and display defeat text.", "Terminate adventure session."]),
    "004ecee0": ("Adventure_PromptConfirmDialog", "Display modal confirmation prompt (Yes, I'm sure).", ["Display confirmation popup menu.", "Return player confirmation choice."]),
    "004ecf94": ("Adventure_DestroyConfirmMenu", "Cleanup popup confirm menu resources.", ["Destroy popup menu handle."]),

    # Group 6: Duel Arena UI & Debug
    "004ecfe5": ("Duel_MainArena_WndProc", "Main duel arena combat window procedure and context debug cheat menus.", ["Handle WM_PAINT to render active duel battlefield.", "Handle WM_COMMAND to process debug menu options (life, reveal hand/library, force win/tie).", "Handle mouse clicks and drag drop card actions.", "Forward unhandled messages to DefWindowProcA."]),
    "004eed47": ("Duel_UpdateWindowScroll", "Update horizontal and vertical card table scroll positions.", ["Calculate visible card boundaries and update scrollbars."]),
    "004eee4e": ("Duel_BringCardWindowToTop", "Bring selected card slot window to front of Z-order.", ["Call BringWindowToTop on selected card control."]),
    "004ef05f": ("Duel_GetBattlefieldClientRect", "Retrieve client pixel bounds of active duel arena.", ["Call GetClientRect on main arena HWND."]),
    "004ef15b": ("Duel_LayoutCardSlots", "Position player and opponent cards across battlefield rows.", ["Calculate card slot X/Y positions for hand, battlefield, and graveyard.", "Reposition child card windows via MoveWindow."]),
    "004ef64b": ("Duel_ScrollLeftButton_Handler", "Scroll duel card battlefield left.", ["Decrement horizontal scroll offset and refresh table."]),
    "004ef740": ("Duel_ScrollRightButton_Handler", "Scroll duel card battlefield right.", ["Increment horizontal scroll offset and refresh table."]),
    "004ef849": ("Duel_HitTestCardSlot", "Perform mouse hit test against battlefield card slots.", ["Translate mouse coordinates to card slot index."]),
    "004ef970": ("Duel_GetHoveredCardSlot", "Query currently hovered card slot index.", ["Return card slot under mouse cursor."]),
    "004efa20": ("Duel_GetCardSlotWindowHandle", "Retrieve HWND for given battlefield card slot.", ["Return child window handle for card slot."]),
    "004efaba": ("Duel_GetTargetSlotWindowHandle", "Retrieve HWND for targeted card slot.", ["Return window handle for target slot."]),
    "004efb3b": ("Duel_PaintBattlefieldBackground", "Paint solid background fill for duel table.", ["Fill client area with battlefield green brush."]),
    "004efd50": ("Duel_LogActionStatusBanner", "Log and display action status banner (CASTING, ACTIVATING, PROCESSING).", ["Format banner string with card name and action type.", "Display banner and refresh screen."]),
    "004f04e0": ("Duel_RegisterChildCardWindowClass", "Register window class for individual interactive card controls.", ["Register MAGICGAME_CardClass window class.", "Load card cursor and background brush."]),
    "004f0597": ("Duel_UnregisterCardWindowClass", "Clean up card control window class resources.", ["Delete card background brush and unregister class."]),
    "004f05c5": ("Duel_ChildCard_WndProc", "Window procedure for individual battlefield card control.", ["Handle WM_PAINT to render card illustration and stats.", "Handle WM_LBUTTONDOWN for card selection and tapping.", "Handle mouse drag and hover highlights."]),
    "004f09c0": ("Duel_GetCardDrawOriginX", "Compute screen X coordinate for card draw animation.", ["Calculate source library screen X position."]),
    "004f0a4a": ("Duel_GetCardDrawOriginY", "Compute screen Y coordinate for card draw animation.", ["Calculate source library screen Y position."]),
    "004f0af6": ("Duel_TriggerCardDrawAnimation", "Launch visual card draw motion interpolation.", ["Initialize motion trajectory from library to hand."]),
    "004f0b50": ("Duel_UpdateCardMotionStep", "Advance card motion frame step during draw/cast animations.", ["Interpolate card position and redraw moving card."]),
    "004f0d90": ("Duel_ResetCardAnimationState", "Reset active animation registers.", ["Clear card animation timers and flags."]),

    # Group 7: Bazaar & Wavelet Art Catalog Loader
    "004f0de8": ("Bazaar_GetCardBaseValue", "Retrieve base shop buy/sell gold valuation for card.", ["Calculate gold price based on card rarity and power level."]),
    "004f0e47": ("Bazaar_SellCardsDialog", "Display interactive card shop / sell dialog.", ["Render list of owned cards with sell values.", "Process player confirmation to sell card for gold.", "Update player gold total."]),
    "004f15c0": ("Catalog_LoadWaveletCardArt", "Open MedArt.cat or SmallArt.cat archive and decompress Haar wavelet illustration.", ["Open catalog archive file.", "Read compressed wavelet coefficients for card ID.", "Decompress 2D Haar wavelets into 8-bit bitmap buffer.", "Return decompressed bitmap pointer."]),
    "004f1910": ("Catalog_ReleaseWaveletLock", "Release concurrency lock on wavelet decompression cache.", ["Leave critical section for wavelet cache."])
}

def export_metadata():
    print(f"Total entries in METADATA: {len(METADATA)}")
    scratch_path = "/Users/ben/.gemini/antigravity/brain/669cec31-26e1-4589-bb85-e02a80bda342/scratch/glue_metadata_full.json"
    with open(scratch_path, "w") as f:
        json.dump(METADATA, f, indent=2)
    
    with open("glue_symbol_map.csv", "w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["Address", "OldName", "NewName"])
        for addr, (new_name, purpose, steps) in sorted(METADATA.items()):
            # We can find old name or default
            w.writerow([addr, f"FUN_{addr}", new_name])
            
    print("Exported metadata to scratch/glue_metadata_full.json and glue_symbol_map.csv")

if __name__ == "__main__":
    export_metadata()
