/*
 * src/platform/api_manifest.c - Win32 Compatibility API Manifest & Diagnostics
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>

#include "shandalar/api_manifest.h"

static bool g_ApiTraceEnabled = false;

static const ApiEntry g_ApiManifest[SHANDALAR_API_MANIFEST_COUNT] = {
    {"AVIFileExit", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"AVIFileGetStream", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"AVIFileInit", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"AVIFileOpenA", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"AVIFileRelease", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"AVIStreamFindSample", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"AVIStreamInfoA", API_SUB_MULTIMEDIA, 1, "magsnd,magvid", true},
    {"AVIStreamRead", API_SUB_MULTIMEDIA, 1, "magsnd,magvid", true},
    {"AVIStreamReadFormat", API_SUB_MULTIMEDIA, 1, "magsnd,magvid", true},
    {"AVIStreamRelease", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"AVIStreamSampleToTime", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"AVIStreamTimeToSample", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"AddFontResourceA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"AdjustWindowRect", API_SUB_USER, 1, "duel,magic,magvid", true},
    {"AnimatePalette", API_SUB_GDI, 1, "magic", true},
    {"AppendMenuA", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"BeginPaint", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"BitBlt", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"BringWindowToTop", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"CallWindowProcA", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"CheckDlgButton", API_SUB_USER, 1, "duel,magic", true},
    {"CheckMenuItem", API_SUB_USER, 1, "deckdll,duel,magic,magvid", true},
    {"CheckRadioButton", API_SUB_USER, 1, "duel,magic", true},
    {"ClientToScreen", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"CloseHandle", API_SUB_KERNEL, 1, "deck,deckdll,duel,magic,magvid,statwin", true},
    {"CompareStringA", API_SUB_KERNEL, 1, "duel", true},
    {"CompareStringW", API_SUB_KERNEL, 1, "duel", true},
    {"CopyFileA", API_SUB_KERNEL, 1, "duel,magic", true},
    {"CopyRect", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"CreateBitmap", API_SUB_GDI, 1, "magic", true},
    {"CreateBrushIndirect", API_SUB_GDI, 1, "magic", true},
    {"CreateCompatibleBitmap", API_SUB_GDI, 1, "deckdll,magic", true},
    {"CreateCompatibleDC", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"CreateDCA", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"CreateDIBSection", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"CreateDirectoryA", API_SUB_KERNEL, 1, "duel", true},
    {"CreateFileA", API_SUB_KERNEL, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"CreateFileMappingA", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"CreateFontA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"CreateFontIndirectA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"CreateHatchBrush", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"CreatePalette", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"CreatePen", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"CreatePenIndirect", API_SUB_GDI, 1, "magic", true},
    {"CreatePolygonRgn", API_SUB_GDI, 1, "duel,magic", true},
    {"CreatePopupMenu", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"CreateRectRgn", API_SUB_GDI, 1, "deckdll", true},
    {"CreateRectRgnIndirect", API_SUB_GDI, 1, "duel,magic", true},
    {"CreateSolidBrush", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"CreateThread", API_SUB_KERNEL, 1, "duel,magic,magvid", true},
    {"CreateWindowExA", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"DPtoLP", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"DebugBreak", API_SUB_KERNEL, 1, "deck,duel", true},
    {"DefWindowProcA", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"DeleteCriticalSection", API_SUB_KERNEL, 1, "deckdll,duel,magic,magsnd,magvid", true},
    {"DeleteDC", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"DeleteFileA", API_SUB_KERNEL, 1, "statwin", true},
    {"DeleteMenu", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"DeleteObject", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"DestroyCursor", API_SUB_USER, 1, "duel,magic", true},
    {"DestroyIcon", API_SUB_USER, 1, "duel,magic", true},
    {"DestroyMenu", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"DestroyWindow", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"DeviceIoControl", API_SUB_KERNEL, 1, "duel,magic", true},
    {"DialogBoxParamA", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"DirectSoundCreate", API_SUB_MULTIMEDIA, 1, "magsnd", true},
    {"DisableThreadLibraryCalls", API_SUB_KERNEL, 1, "magsnd", true},
    {"DispatchMessageA", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"DrawDibBegin", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"DrawDibClose", API_SUB_MULTIMEDIA, 1, "magvid,statwin", true},
    {"DrawDibDraw", API_SUB_MULTIMEDIA, 1, "magvid,statwin", true},
    {"DrawDibEnd", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"DrawDibOpen", API_SUB_MULTIMEDIA, 1, "magvid,statwin", true},
    {"DrawDibStart", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"DrawDibStop", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"DrawFocusRect", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"DrawTextA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"DuplicateHandle", API_SUB_KERNEL, 1, "magic", true},
    {"Ellipse", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"EnableMenuItem", API_SUB_USER, 1, "duel,magic", true},
    {"EnableWindow", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"EndDialog", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"EndPaint", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"EnterCriticalSection", API_SUB_KERNEL, 1, "deckdll,duel,magic,magsnd,magvid", true},
    {"EnumChildWindows", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"ExitProcess", API_SUB_KERNEL, 1, "deck,duel", true},
    {"ExitThread", API_SUB_KERNEL, 1, "duel,magic", true},
    {"FillRect", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"FindResourceA", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"FindWindowA", API_SUB_USER, 1, "deck,duel,magic", true},
    {"FindWindowExA", API_SUB_USER, 1, "magic", true},
    {"FlushFileBuffers", API_SUB_KERNEL, 1, "deck,duel", true},
    {"FormatMessageA", API_SUB_KERNEL, 1, "magvid", true},
    {"FrameRect", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"FreeEnvironmentStringsA", API_SUB_KERNEL, 1, "deck,duel", true},
    {"FreeEnvironmentStringsW", API_SUB_KERNEL, 1, "deck,duel", true},
    {"FreeLibrary", API_SUB_KERNEL, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"GdiFlush", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"GdiGetBatchLimit", API_SUB_GDI, 1, "magic", true},
    {"GdiSetBatchLimit", API_SUB_GDI, 1, "magic", true},
    {"GetACP", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetActiveWindow", API_SUB_USER, 1, "magvid", true},
    {"GetAsyncKeyState", API_SUB_USER, 1, "magic", true},
    {"GetCPInfo", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetCapture", API_SUB_USER, 1, "duel,magic", true},
    {"GetCharABCWidthsA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"GetCharWidthA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"GetClassNameA", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetClientRect", API_SUB_USER, 1, "deckdll,duel,magic,magvid", true},
    {"GetCommandLineA", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetCurrentDirectoryA", API_SUB_KERNEL, 1, "duel,magic", true},
    {"GetCurrentProcess", API_SUB_KERNEL, 1, "deck,duel,magic,magvid,statwin", true},
    {"GetCurrentThread", API_SUB_KERNEL, 1, "duel,magic", true},
    {"GetCursorPos", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetDC", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"GetDateFormatA", API_SUB_KERNEL, 1, "deckdll", true},
    {"GetDesktopWindow", API_SUB_USER, 1, "deckdll", true},
    {"GetDeviceCaps", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"GetDlgCtrlID", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetDlgItem", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetDlgItemInt", API_SUB_USER, 1, "duel,magic", true},
    {"GetDlgItemTextA", API_SUB_USER, 1, "duel,magic", true},
    {"GetDoubleClickTime", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetDriveTypeA", API_SUB_KERNEL, 1, "magic,statwin", true},
    {"GetEnvironmentStrings", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetEnvironmentStringsW", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetExitCodeThread", API_SUB_KERNEL, 1, "duel,magic", true},
    {"GetFileSize", API_SUB_KERNEL, 1, "deckdll,duel,magic,magvid", true},
    {"GetFileType", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetFocus", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetKeyState", API_SUB_USER, 1, "duel,magic", true},
    {"GetLastError", API_SUB_KERNEL, 1, "deck,duel,magvid,statwin", true},
    {"GetLocalTime", API_SUB_KERNEL, 1, "duel", true},
    {"GetMenu", API_SUB_USER, 1, "magvid", true},
    {"GetMenuItemCount", API_SUB_USER, 1, "duel,magic", true},
    {"GetMessageA", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetMessageTime", API_SUB_USER, 1, "duel,magic", true},
    {"GetModuleFileNameA", API_SUB_KERNEL, 1, "deck,deckdll,duel,magic", true},
    {"GetModuleHandleA", API_SUB_KERNEL, 1, "deck,deckdll,duel,magic", true},
    {"GetNearestPaletteIndex", API_SUB_KERNEL, 1, "magvid,statwin", true},
    {"GetOEMCP", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetObjectA", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"GetOpenFileNameA", API_SUB_USER, 1, "duel,magvid", true},
    {"GetPaletteEntries", API_SUB_GDI, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"GetParent", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetPixel", API_SUB_GDI, 1, "magic", true},
    {"GetPriorityClass", API_SUB_KERNEL, 1, "statwin", true},
    {"GetPrivateProfileIntA", API_SUB_CONFIG, 1, "deckdll,duel,magic", true},
    {"GetPrivateProfileStringA", API_SUB_CONFIG, 1, "deckdll,duel,magic", true},
    {"GetProcAddress", API_SUB_KERNEL, 1, "deck,deckdll,duel,magic,magvid,statwin", true},
    {"GetSaveFileNameA", API_SUB_USER, 1, "duel,magic", true},
    {"GetScrollPos", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetScrollRange", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetStartupInfoA", API_SUB_KERNEL, 1, "deck,duel,magic", true},
    {"GetStdHandle", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetStockObject", API_SUB_GDI, 1, "deckdll,duel,magic,statwin", true},
    {"GetStringTypeA", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetStringTypeW", API_SUB_KERNEL, 1, "deck,duel", true},
    {"GetSubMenu", API_SUB_USER, 1, "magvid", true},
    {"GetSysColor", API_SUB_USER, 1, "deckdll", true},
    {"GetSystemMetrics", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"GetSystemTime", API_SUB_KERNEL, 1, "duel", true},
    {"GetTextAlign", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"GetTextExtentPoint32A", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"GetTextExtentPointA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"GetTextMetricsA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"GetThreadPriority", API_SUB_KERNEL, 1, "magic", true},
    {"GetTickCount", API_SUB_KERNEL, 1, "duel,magic", true},
    {"GetTimeZoneInformation", API_SUB_KERNEL, 1, "duel", true},
    {"GetTopWindow", API_SUB_USER, 1, "deckdll", true},
    {"GetVersion", API_SUB_KERNEL, 1, "deck,deckdll,duel,magic,magsnd,magvid,statwin", true},
    {"GetWindow", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetWindowDC", API_SUB_USER, 1, "duel,magic", true},
    {"GetWindowLongA", API_SUB_USER, 1, "deckdll,duel,magic,magvid", true},
    {"GetWindowRect", API_SUB_USER, 1, "deckdll,duel,magic,magvid", true},
    {"GetWindowTextA", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetWindowThreadProcessId", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"GetWindowWord", API_SUB_USER, 1, "deckdll", true},
    {"GlobalAlloc", API_SUB_KERNEL, 1, "deckdll,duel,magic,magsnd,magvid,statwin", true},
    {"GlobalFree", API_SUB_KERNEL, 1, "deckdll,duel,magic,magsnd,magvid,statwin", true},
    {"GlobalHandle", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"GlobalLock", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"GlobalUnlock", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"HeapAlloc", API_SUB_KERNEL, 1, "deck,duel", true},
    {"HeapCreate", API_SUB_KERNEL, 1, "deck,duel", true},
    {"HeapDestroy", API_SUB_KERNEL, 1, "deck,duel", true},
    {"HeapFree", API_SUB_KERNEL, 1, "deck,duel", true},
    {"HeapReAlloc", API_SUB_KERNEL, 1, "deck,duel", true},
    {"HeapValidate", API_SUB_KERNEL, 1, "deck,duel", true},
    {"ICClose", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"ICDrawBegin", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"ICLocate", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"ICSendMessage", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"InflateRect", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"InitializeCriticalSection", API_SUB_KERNEL, 1, "deckdll,duel,magic,magsnd,magvid", true},
    {"InsertMenuA", API_SUB_USER, 1, "deckdll", true},
    {"InterlockedDecrement", API_SUB_KERNEL, 1, "deck,duel", true},
    {"InterlockedIncrement", API_SUB_KERNEL, 1, "deck,duel", true},
    {"IntersectClipRect", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"IntersectRect", API_SUB_USER, 1, "statwin", true},
    {"InvalidateRect", API_SUB_GDI, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"IsBadReadPtr", API_SUB_KERNEL, 1, "deck,duel", true},
    {"IsBadWritePtr", API_SUB_KERNEL, 1, "deck,duel", true},
    {"IsDlgButtonChecked", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"IsIconic", API_SUB_USER, 1, "duel,magic", true},
    {"IsRectEmpty", API_SUB_USER, 1, "duel,magic", true},
    {"IsWindowVisible", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"KillTimer", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"LCMapStringA", API_SUB_KERNEL, 1, "deck,duel", true},
    {"LCMapStringW", API_SUB_KERNEL, 1, "deck,duel", true},
    {"LPtoDP", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"LeaveCriticalSection", API_SUB_KERNEL, 1, "deckdll,duel,magic,magsnd,magvid", true},
    {"LineTo", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"LoadAcceleratorsA", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"LoadBitmapA", API_SUB_KERNEL, 1, "duel,magic", true},
    {"LoadCursorA", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"LoadIconA", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"LoadLibraryA", API_SUB_KERNEL, 1, "deck,deckdll,duel,magic,magvid,statwin", true},
    {"LoadResource", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"LocalFree", API_SUB_KERNEL, 1, "magvid", true},
    {"LockResource", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"LockWindowUpdate", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"MCIWndCreateA", API_SUB_MULTIMEDIA, 1, "duel,magic", true},
    {"MapViewOfFile", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"MapWindowPoints", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"MessageBeep", API_SUB_USER, 1, "deckdll,magic", true},
    {"MessageBoxA", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"ModifyMenuA", API_SUB_USER, 1, "duel,magic", true},
    {"MoveToEx", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"MoveWindow", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"MultiByteToWideChar", API_SUB_KERNEL, 1, "deck,duel", true},
    {"OffsetRect", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"OffsetViewportOrgEx", API_SUB_GDI, 1, "duel,magic", true},
    {"Ordinal_17", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"OutputDebugStringA", API_SUB_KERNEL, 1, "deck,deckdll,duel,magic", true},
    {"PeekMessageA", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"PostMessageA", API_SUB_USER, 1, "deck,deckdll,duel,magic,magsnd,magvid", true},
    {"PostQuitMessage", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"PtInRect", API_SUB_USER, 1, "deckdll,duel,magic,magvid", true},
    {"ReadFile", API_SUB_KERNEL, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"RealizePalette", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"Rectangle", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"RegCloseKey", API_SUB_CONFIG, 1, "deckdll,duel,magic", true},
    {"RegCreateKeyExA", API_SUB_CONFIG, 1, "deckdll,duel,magic", true},
    {"RegFlushKey", API_SUB_CONFIG, 1, "deckdll,duel,magic", true},
    {"RegOpenKeyExA", API_SUB_CONFIG, 1, "deckdll,duel,magic", true},
    {"RegQueryValueExA", API_SUB_CONFIG, 1, "deckdll,duel,magic", true},
    {"RegSetValueExA", API_SUB_CONFIG, 1, "deckdll,duel,magic", true},
    {"RegisterClassA", API_SUB_CONFIG, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"ReleaseCapture", API_SUB_USER, 1, "duel,magic", true},
    {"ReleaseDC", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"RemoveFontResourceA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"RemoveMenu", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"RestoreDC", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"RoundRect", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"RtlUnwind", API_SUB_KERNEL, 1, "deck,duel", true},
    {"SHAppBarMessage", API_SUB_USER, 1, "duel,magic", true},
    {"SaveDC", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"ScreenToClient", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"ScrollWindow", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"SelectClipRgn", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SelectObject", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"SelectPalette", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"SendDlgItemMessageA", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"SendMessageA", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"SetActiveWindow", API_SUB_USER, 1, "duel,magic", true},
    {"SetBitmapDimensionEx", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetBkColor", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetBkMode", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetCapture", API_SUB_USER, 1, "duel,magic", true},
    {"SetClassLongA", API_SUB_USER, 1, "duel,magic", true},
    {"SetConsoleCtrlHandler", API_SUB_KERNEL, 1, "deck,duel", true},
    {"SetCurrentDirectoryA", API_SUB_KERNEL, 1, "duel", true},
    {"SetCursor", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"SetCursorPos", API_SUB_USER, 1, "magic", true},
    {"SetDIBColorTable", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetDIBits", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetDIBitsToDevice", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetDlgItemInt", API_SUB_USER, 1, "duel,magic", true},
    {"SetDlgItemTextA", API_SUB_USER, 1, "duel,magic", true},
    {"SetEndOfFile", API_SUB_KERNEL, 1, "duel", true},
    {"SetEnvironmentVariableA", API_SUB_KERNEL, 1, "duel", true},
    {"SetFilePointer", API_SUB_KERNEL, 1, "deck,duel", true},
    {"SetFocus", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"SetForegroundWindow", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"SetHandleCount", API_SUB_KERNEL, 1, "deck,duel", true},
    {"SetMapMode", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetPaletteEntries", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetParent", API_SUB_USER, 1, "deckdll", true},
    {"SetPixel", API_SUB_GDI, 1, "magic", true},
    {"SetPixelV", API_SUB_GDI, 1, "magic", true},
    {"SetPriorityClass", API_SUB_KERNEL, 1, "magvid,statwin", true},
    {"SetROP2", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetRect", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"SetRectRgn", API_SUB_GDI, 1, "deckdll", true},
    {"SetScrollPos", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"SetScrollRange", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"SetStdHandle", API_SUB_KERNEL, 1, "deck,duel", true},
    {"SetStretchBltMode", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"SetSystemPaletteUse", API_SUB_USER, 1, "magic,magvid,statwin", true},
    {"SetTextAlign", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetTextColor", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetThreadPriority", API_SUB_KERNEL, 1, "duel,magic,magvid", true},
    {"SetTimer", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"SetViewportExtEx", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetViewportOrgEx", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetWindowExtEx", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetWindowLongA", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"SetWindowOrgEx", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"SetWindowPos", API_SUB_USER, 1, "deckdll,duel,magic,magvid", true},
    {"SetWindowRgn", API_SUB_KERNEL, 1, "duel,magic", true},
    {"SetWindowTextA", API_SUB_USER, 1, "deckdll,duel,magic,magvid", true},
    {"SetWindowWord", API_SUB_USER, 1, "deckdll", true},
    {"ShowCursor", API_SUB_USER, 1, "magic", true},
    {"ShowWindow", API_SUB_USER, 1, "deckdll,duel,magic,magvid,statwin", true},
    {"Sleep", API_SUB_KERNEL, 1, "deckdll,duel,magic,magsnd,magvid,statwin", true},
    {"StretchBlt", API_SUB_GDI, 1, "deckdll,duel,magic,magvid", true},
    {"TerminateProcess", API_SUB_KERNEL, 1, "deck,duel", true},
    {"TextOutA", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"TrackPopupMenu", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"TranslateAcceleratorA", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"TranslateMessage", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"UnhandledExceptionFilter", API_SUB_KERNEL, 1, "deck,duel", true},
    {"UnionRect", API_SUB_USER, 1, "duel,magic,statwin", true},
    {"UnmapViewOfFile", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"UnrealizeObject", API_SUB_GDI, 1, "deckdll,duel,magic", true},
    {"UnregisterClassA", API_SUB_USER, 1, "magvid,statwin", true},
    {"UpdateWindow", API_SUB_USER, 1, "deckdll,duel,magic,statwin", true},
    {"VirtualAlloc", API_SUB_KERNEL, 1, "deck,duel", true},
    {"VirtualFree", API_SUB_KERNEL, 1, "deck,duel", true},
    {"WaitForSingleObject", API_SUB_KERNEL, 1, "duel,magic", true},
    {"WideCharToMultiByte", API_SUB_KERNEL, 1, "deck,duel", true},
    {"WinHelpA", API_SUB_USER, 1, "duel,magic", true},
    {"WindowFromPoint", API_SUB_USER, 1, "deckdll,duel,magic", true},
    {"WriteFile", API_SUB_KERNEL, 1, "deck,duel,magvid,statwin", true},
    {"_lclose", API_SUB_KERNEL, 1, "magvid", true},
    {"_lopen", API_SUB_KERNEL, 1, "magvid", true},
    {"lstrcatA", API_SUB_KERNEL, 1, "magvid", true},
    {"lstrcpyA", API_SUB_KERNEL, 1, "magvid", true},
    {"lstrlenA", API_SUB_KERNEL, 1, "deckdll,duel,magic,magvid", true},
    {"mmioAdvance", API_SUB_MULTIMEDIA, 1, "magsnd", true},
    {"mmioAscend", API_SUB_MULTIMEDIA, 1, "magsnd", true},
    {"mmioClose", API_SUB_MULTIMEDIA, 1, "magsnd,magvid", true},
    {"mmioDescend", API_SUB_MULTIMEDIA, 1, "magsnd,magvid", true},
    {"mmioGetInfo", API_SUB_MULTIMEDIA, 1, "magsnd", true},
    {"mmioOpenA", API_SUB_MULTIMEDIA, 1, "magsnd,magvid", true},
    {"mmioRead", API_SUB_MULTIMEDIA, 1, "magsnd,magvid", true},
    {"mmioSeek", API_SUB_MULTIMEDIA, 1, "magsnd", true},
    {"mmioSetInfo", API_SUB_MULTIMEDIA, 1, "magsnd", true},
    {"timeBeginPeriod", API_SUB_MULTIMEDIA, 1, "magic,magsnd,magvid", true},
    {"timeEndPeriod", API_SUB_MULTIMEDIA, 1, "magic,magsnd,magvid", true},
    {"timeGetDevCaps", API_SUB_MULTIMEDIA, 1, "magsnd,magvid", true},
    {"timeGetTime", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"timeKillEvent", API_SUB_MULTIMEDIA, 1, "magic,magsnd", true},
    {"timeSetEvent", API_SUB_MULTIMEDIA, 1, "magic,magsnd", true},
    {"waveOutWrite", API_SUB_MULTIMEDIA, 1, "magvid", true},
    {"wsprintfA", API_SUB_KERNEL, 1, "deckdll,duel,magic", true},
    {"wvsprintfA", API_SUB_KERNEL, 1, "magvid", true},
};

const ApiEntry* Platform_GetApiManifest(size_t *out_count)
{
    if (out_count) *out_count = SHANDALAR_API_MANIFEST_COUNT;
    return g_ApiManifest;
}

const ApiEntry* Platform_FindApiEntry(const char *name)
{
    if (!name) return NULL;
    for (size_t i = 0; i < SHANDALAR_API_MANIFEST_COUNT; i++) {
        if (strcmp(g_ApiManifest[i].name, name) == 0) {
            return &g_ApiManifest[i];
        }
    }
    return NULL;
}

void Platform_TraceApi(const char *api_name, const char *caller_context)
{
    if (!g_ApiTraceEnabled || !api_name) return;
    static char s_TracedApis[256][64];
    static size_t s_TracedCount = 0;

    for (size_t i = 0; i < s_TracedCount; i++) {
        if (strcmp(s_TracedApis[i], api_name) == 0) return;
    }

    if (s_TracedCount < 256) {
        strncpy(s_TracedApis[s_TracedCount++], api_name, 63);
    }

    fprintf(stderr, "[Win32Compat Trace] API: %s called from: %s\n",
            api_name, caller_context ? caller_context : "unknown");
}

void Platform_SetApiTraceEnabled(bool enabled)
{
    g_ApiTraceEnabled = enabled;
}

bool Platform_IsApiTraceEnabled(void)
{
    return g_ApiTraceEnabled;
}
